### ISSUE TITLE
Version 0.1.100 and 0.1.101 don't start on osmc in raspberry PI4

### ISSUE THREAD

**Issue by ShinoAce** [elgatito/plugin.video.elementum#1028]
version 0.1.99 work fine but version 0.1.100 and version 0.1.101 don't start
Kodi version 20.3
Systeme OSMC last update

log file error
`2024-04-21 14:46:57.212 T:613     error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'distutils.dir_util'
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.elementum/service.py", line 4, in <module>
                                                       from elementum import service, config
                                                     File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/service.py", line 5, in <module>
                                                       from elementum.monitor import ElementumMonitor
                                                     File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/monitor.py", line 10, in <module>
                                                       from elementum.daemon import shutdown
                                                     File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 17, in <module>
                                                       from distutils.dir_util import copy_tree
                                                   ModuleNotFoundError: No module named 'distutils.dir_util'
                                                   -->End of Python script error report<--
                                                   `

**Comment by antonsoroko** [comment]
@ShinoAce 
this seems to be OSMC specific issue
also there is similar report: https://discourse.osmc.tv/t/2-addons-not-working-with-distutils-module-dependency/93431/9

can you run this command in terminal: `python` (or `python3`) and write here which version of python you have?
my guess - you have 3.12 and it does not have `distutils` module anymore.

---

@elgatito i see that "[distutils](https://docs.python.org/3.10/library/distutils.html#module-distutils) is deprecated with removal planned for Python 3.12." so maybe it makes sense to migrate to something else anyway.

**Comment by elgatito** [comment]
@antonsoroko 
https://stackoverflow.com/a/73439464

I guess we need to make a solution that would work on both Py3/Py2. 

Something like this: https://github.com/elgatito/plugin.video.elementum/blob/master/resources/site-packages/elementum/daemon.py#L29-L35

To detect what we can do and so use that specific function.

**Comment by antonsoroko** [comment]
@elgatito 
We already use shutil in daemon.py for different file operations and it works in py2 and py3.
so I guess in this particular case we can simply replace distutils with shutils, thus no need to "detect" what is available.

**Comment by elgatito** [comment]
I will try different approaches. Have few more hot fixes to do for the next version.

**Comment by ShinoAce** [comment]
Sorty for the delay. My python version on the osmc is 3.9.2

**Comment by dineshalphaque** [comment]
> version 0.1.99 work fine but version 0.1.100 and version 0.1.101 don't start Kodi version 20.3 Systeme OSMC last update

I'm on the latest OSMC build running Elementum 0.1.101 without any problems.

**Comment by antonsoroko** [comment]
thanks for info!
this is strange then. 3.9.2 should have distutils. and if it works for @dineshalphaque , then maybe @ShinoAce has something broken in his/her system, like update was applied partially.

but we still would need to replace distutils with shutils in future.

**Comment by elgatito** [comment]
@antonsoroko @ShinoAce I've pushed a very simple fix for `distutils` replacement.

**Comment by ShinoAce** [comment]
i'm sure is not linux X64 is an armV8 but can u point me where do i find the log file for elementum
This is the first liens of the kodi log may be u will find whatarchitecture i'm using cause is bit confusing for me . I'm sur it's an ARMv8 X64 but in the log file it say kodi 32-bits.
`2024-04-21 15:31:47.434 T:570      info <general>: -----------------------------------------------------------------------
2024-04-21 15:31:47.434 T:570      info <general>: Starting Kodi (20.3). Platform: Linux ARM (Thumb) 32-bit
2024-04-21 15:31:47.434 T:570      info <general>: Using Release Kodi x32
2024-04-21 15:31:47.434 T:570      info <general>: Kodi compiled 2024-01-28 by GCC 10.2.1 for Linux ARM (Thumb) 32-bit version 5.15.92 (331612)
2024-04-21 15:31:47.434 T:570      info <general>: Running on BCM2835 with Open Source Media Center 2024.02-1, kernel: Linux ARM 32-bit version 5.15.92-1-osmc
2024-04-21 15:31:47.459 T:570      info <general>: FFmpeg version/source: 12b4775-kodi-4.4.1-Nexus-Alpha1
2024-04-21 15:31:47.459 T:570      info <general>: 4 CPU cores available
2024-04-21 15:31:47.459 T:570      info <general>: ARM Features: Neon disabled
2024-04-21 15:31:47.459 T:570      info <general>: special://xbmc/ is mapped to: /usr/share/kodi
2024-04-21 15:31:47.459 T:570      info <general>: special://xbmcbin/ is mapped to: /usr/lib/kodi
2024-04-21 15:31:47.459 T:570      info <general>: special://xbmcbinaddons/ is mapped to: /usr/lib/kodi/addons
2024-04-21 15:31:47.459 T:570      info <general>: special://masterprofile/ is mapped to: /home/osmc/.kodi/userdata
2024-04-21 15:31:47.459 T:570      info <general>: special://envhome/ is mapped to: /home/osmc
2024-04-21 15:31:47.459 T:570      info <general>: special://home/ is mapped to: /home/osmc/.kodi
2024-04-21 15:31:47.459 T:570      info <general>: special://temp/ is mapped to: /home/osmc/.kodi/temp
2024-04-21 15:31:47.459 T:570      info <general>: special://logpath/ is mapped to: /home/osmc/.kodi/temp
2024-04-21 15:31:47.459 T:570      info <general>: Webserver extra whitelist paths: 
2024-04-21 15:31:47.459 T:570      info <general>: The executable running is: /usr/lib/kodi/kodi.bin
2024-04-21 15:31:47.459 T:570      info <general>: Local hostname: osmc
2024-04-21 15:31:47.459 T:570      info <general>: Log File is located: /home/osmc/.kodi/temp/kodi.log`

The uname -a command returne 
`xxxxxxxx@xxxxx:~$ uname -a
Linux osmc 5.15.92-1-osmc #1 SMP PREEMPT Tue Jul 25 00:03:42 UTC 2023 aarch64 GNU/Linux`

Hope that will help

**Comment by antonsoroko** [comment]
@ShinoAce 
should be like this:
```
debug <general>: [plugin.video.elementum] Automatically detected platform: linux-x64. 
Returning: {'auto_arch': '64-bit', 'arch': 'x64', 'os': 'linux', 'version': '', 'kodi': 20, 
'build': '20.2 Debian package version: 2:20.2+dfsg-4', 'fork': True, 'machine': '', 'system': '', 'platform': ''}
```

**Comment by antonsoroko** [comment]
wild guess: if it is linux-armv7 -  https://disk.yandex.by/d/CZUMsXPnm-EUiw

**Comment by ShinoAce** [comment]
ok it works with the version armv7. I think the last commit solve the probleme

**Comment by BinaryNumber** [comment]
Exact same error as @ShinoAce in log file on my side with latest OSMC on Rpi 4 and Elementum addon version 0.1.101

Glad to see a fix is already developed. Do you know when it will be officially released please?

**Comment by elgatito** [comment]
@ShinoAce @BinaryNumber Please, use version 0.1.102 with a fix.

**Comment by BinaryNumber** [comment]
> @ShinoAce @BinaryNumber Please, use version 0.1.102 with a fix.

I confirm update to 0.1.102 version fix the issue on my side

**Comment by ShinoAce** [comment]
Me too version 0.1.102 work fine for me
