### ISSUE TITLE
crash on open , kodi for debian version (20) in ubuntu 24.04

### ISSUE THREAD

**Issue by atomsk81** [elgatito/plugin.video.elementum#1051]
elementum and elementum burst appear to be installing OK but upon startup of kodi I get the following in logs
i get:

2024-06-21 09:07:10.929 T:54091   error <general>: ----------------------------------------
2024-06-21 09:07:10.929 T:54091   error <general>:
2024-06-21 09:07:10.929 T:54091   error <general>: Exception occurred during processing of request from
2024-06-21 09:07:10.929 T:54091   error <general>:
2024-06-21 09:07:10.929 T:54091   error <general>: ('127.0.0.1', 36194)
2024-06-21 09:07:10.929 T:54091   error <general>:
2024-06-21 09:07:10.930 T:54006 warning <general>: [plugin.video.elementum] INFO  main         ▶ func8            Updating Kodi add-on repositories...
2024-06-21 09:07:10.931 T:54091   error <general>: Traceback (most recent call last):
2024-06-21 09:07:10.931 T:54091   error <general>:
2024-06-21 09:07:10.952 T:54091   error <general>:   File "/usr/lib/python3.12/socketserver.py", line 692, in process_request_thread
                                                       self.finish_request(request, client_address)
2024-06-21 09:07:10.953 T:54091   error <general>:
2024-06-21 09:07:10.953 T:54091   error <general>:   File "/usr/lib/python3.12/socketserver.py", line 362, in finish_request
                                                       self.RequestHandlerClass(request, client_address, self)
2024-06-21 09:07:10.953 T:54091   error <general>:
2024-06-21 09:07:10.953 T:54091   error <general>:   File "/usr/lib/python3.12/socketserver.py", line 761, in __init__
                                                       self.handle()
2024-06-21 09:07:10.953 T:54091   error <general>:
2024-06-21 09:07:10.953 T:54091   error <general>:   File "/usr/lib/python3.12/http/server.py", line 438, in handle
                                                       self.handle_one_request()
2024-06-21 09:07:10.953 T:54091   error <general>:
2024-06-21 09:07:10.953 T:54091   error <general>:   File "/usr/lib/python3.12/http/server.py", line 404, in handle_one_request
                                                       self.raw_requestline = self.rfile.readline(65537)
                                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 09:07:10.953 T:54091   error <general>:
2024-06-21 09:07:10.953 T:54091   error <general>:   File "/usr/lib/python3.12/socket.py", line 707, in readinto
                                                       return self._sock.recv_into(b)
                                                             ^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 09:07:10.953 T:54091   error <general>:
2024-06-21 09:07:10.953 T:54091   error <general>: ConnectionResetError: [Errno 104] Connection reset by peer
2024-06-21 09:07:10.953 T:54091   error <general>:
2024-06-21 09:07:10.953 T:54091   error <general>: ----------------------------------------
2024-06-21 09:07:10.953 T:54091   error <general>:

also when i try to start elementum kodi freezes and then crashes. Last logged event is  

`info <general>: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY`
  i don't see any other errors

**Comment by antonsoroko** [comment]
@atomsk81 

not sure that this is elementum issue since nothing in your log indicate that.
try to make proper debug log - guide was in issue template. maybe then we will see more info.

i also use Ubuntu 24.04 and their kodi has nasty bug - see https://bugs.launchpad.net/ubuntu/+source/kodi/+bug/2063358
so i had to apply patch and recompile it, see my guide in that issue.

with patched kodi version - elementum works fine.

**Comment by elgatito** [comment]
@antonsoroko "fun" comment: https://bugs.launchpad.net/ubuntu/+source/kodi/+bug/2063358/comments/9

**Comment by antonsoroko** [comment]
@elgatito yeah, sad situation. i guess people use flatpak version on ubuntu 24.04. 
i have both - flatpak version works unstable with elementum, b/c elementun is a separate process and sometimes flatpak cage/container kills it on very start.

**Comment by i300220** [comment]
@elgatito Hi,

Just wondering whether elementum could be more stable with Kodi flatpak version?

I have Fedora 40 with Kodi 21 and the dreaded python 3.12 therefore I had no choice but to delete the F40 Kodi instance and install Flatpak's.  Kodi crashes like 10 times a day, usually when starting, sometimes after playing a video, elementum not always starting, elementum timing out, elementun stopping reporting download progress, elementum randomly updating trakt history, etc.  The list of issues is endless and there is absolutely nothing useful in the crashlog

When I disable elementum + burst, Kodi is stable again.  I only enable them when I require them.  Annoying workaround.

I also have elementum installed on Win 7 and Kodi 20.5 and it's rock stable however it's sad to have to switch to window only to use Kodi+elementum

Thanks for all that amazing work you've done on it.  It's the most useful addon I've ever seen because it does find the HD versions of tv/movies whereas scrapers usually find the smaller (in size) ones.

Best!

**Comment by antonsoroko** [comment]
@i300220 from what you described i would make a guess that flatpak jail for kodi is configured to kill all unnecessary processes (like elementum) leaving only kodi process. but i am not flatpak expert and i do not see anything suspicious in their code for kodi container - https://github.com/flathub/tv.kodi.Kodi/tree/master

If there was crash - there should be crash log in ${XDG_DATA_HOME} (e.g. kodi_crashlog-20240723_222243.log) - you can post it https://github.com/elgatito/plugin.video.elementum/issues/1058, maybe it will help to identify the issue.

**Comment by i300220** [comment]
Hi,

I appreciate your analysis.  I will provide more info.

Unfortunately, crashlogs are totally useless in the flatpak version, they are merely copies of kodi.log.  Sorry.  One would have to compile kodi flatpak with debug information to achieve anything meaningful.

Workaround.  I disable elementum and re-enable it whenever I need it, e.g. once a week, then re-disable it afterwards.  The main thing is not let it to start with Kodi.  I can live with that.  And I stick to kernel 6.8.7.

Additionally, there is a VRAM (amdgpu) linux kernel bug mentioned in https://gitlab.freedesktop.org/drm/amd/-/issues/3599 and https://github.com/flathub/tv.kodi.Kodi/issues/292  resulting in Kodi crashing whenever one plays a video.  Kernel versions after 6.8.7 are prone to this, particularly the whole 6.10 branch.

**Comment by antonsoroko** [comment]
@i300220 please try with 
Elementum > Settings > Advanced > "Force start as library" toggled

This feature was created specifically for new androids where new Kodi (complied with new android sdk) was not permitted to run binaries. 
As I have seen it works a bit less stable than separate process, but stable enough. 
It should fix issue when flatpak kills Elementum process.

**Comment by antonsoroko** [comment]
@i300220 do not try it :-) it is very unstable, so it is not a solution. 
Anyway, for flatpak related issues see https://github.com/elgatito/plugin.video.elementum/issues/1058

----

This issue is about debian version 20 with python 3.12.
The solution for it was described above.

**Comment by antonsoroko** [comment]
so kodi was finally fixed in ubuntu 24.04 but only in "noble-proposed" repo.
see comment 10 for details and for info how to install it:
https://bugs.launchpad.net/ubuntu/+source/kodi/+bug/2079914

**Comment by antonsoroko** [comment]
new kodi package was moved to "noble-updates", so now all users should get it.
i think we can close this issue.

**Comment by elgatito** [comment]
Anyway, nothing to do from Elementum. 
Closing the issue.
