### ISSUE TITLE
Does not play anything

### ISSUE THREAD

**Issue by hoshsadiq** [elgatito/plugin.video.elementum#23]
Latest version keeps buffering up to 100% but then crashes with the error
> One or more items failed to play. Check the logs for more information about this message.
The following is (I presume) the relevant error log:
```
22:25:29.814 T:2088786208  NOTICE: [plugin.video.elementum] [36mDEBU  torrent      ▶ progressEvent    [0mPR: 432133/0; "Downloading" = 3.22
22:25:30.325 T:18446744072099461408   ERROR: CCurlFile::Stat - Failed: Couldn't connect to server(7) for http://localhost:65220/files/----clipped----.mkv
22:25:30.330 T:18446744071693433120  NOTICE: Creating InputStream
22:25:30.517 T:18446744071693433120   ERROR: CCurlFile::FillBuffer - Failed: Couldn't connect to server(7)
22:25:30.518 T:18446744071693433120   ERROR: CCurlFile::Open failed with code 0 for http://localhost:65220/files/----clipped----.mkv
22:25:30.814 T:2088786208  NOTICE: [plugin.video.elementum] [36mDEBU  torrent      ▶ progressEvent    [0mPR: 471454/0; "Downloading" = 3.29
22:25:31.436 T:18446744071693433120   ERROR: CCurlFile::FillBuffer - Failed: Couldn't connect to server(7)
22:25:31.437 T:18446744071693433120   ERROR: CCurlFile::Open failed with code 0 for http://localhost:65220/files/----clipped----.mkv
22:25:31.440 T:18446744071693433120   ERROR: Open - failed to open source <http://localhost:65220/files/----clipped----.mkv>
22:25:31.454 T:18446744071693433120   ERROR: CVideoPlayer::OpenInputStream - error opening [http://localhost:65220/files/----clipped----.mkv]
22:25:31.455 T:18446744071693433120  NOTICE: CVideoPlayer::OnExit()
22:25:31.481 T:18446744072099461408   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.elementum/show/----clipped---/season/7/episode/6/links]
22:25:31.485 T:18446744072099461408  NOTICE: CVideoPlayer::CloseFile()
22:25:31.486 T:18446744072099461408  NOTICE: VideoPlayer: waiting for threads to exit
22:25:31.486 T:18446744072099461408  NOTICE: VideoPlayer: finished waiting
22:25:31.488 T:18446744072099461408  NOTICE: CVideoPlayer::CloseFile()
22:25:31.488 T:18446744072099461408  NOTICE: VideoPlayer: waiting for threads to exit
22:25:31.488 T:18446744072099461408  NOTICE: VideoPlayer: finished waiting
22:25:31.813 T:2095671584   ERROR: EXCEPTION: XBMC is not playing any media file
```

**Comment by hoshsadiq** [comment]
Oh forgot to mention, this is on Android TV. ARMv7:

```$ adb shell cat /proc/cpuinfo
processor	: 0
model name	: ARMv7 Processor rev 2 (v7l)
Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 2

processor	: 1
model name	: ARMv7 Processor rev 2 (v7l)
Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 2

processor	: 2
model name	: ARMv7 Processor rev 2 (v7l)
Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 2

processor	: 3
model name	: ARMv7 Processor rev 2 (v7l)
Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 2

Hardware	: MT5891
Revision	: 0000
Serial		: 0000000000000000```

**Comment by elgatito** [comment]
Please, enable debug mode and post the full log of playing anything.
http://kodi.wiki/view/Log_file/Easy

**Comment by hoshsadiq** [comment]
Here you go: https://paste.ee/p/SEJGR

**Comment by elgatito** [comment]
Can't see any problem in that log, and it's not full. 
You can try the latest version and upload the whole kodi.log somewhere if it's too big.

**Comment by hoshsadiq** [comment]
Could it be related to this bit:
```
05:36:14.713 T:18446744071693306144  NOTICE: [plugin.video.elementum] DEBU  torrent      ▶ progressEvent    PR: 688128/0; "Buffering" = 72.80
05:36:14.973 T:18446744071693306144  NOTICE: [plugin.video.elementum] DEBU  torrent      ▶ progressEvent    PR: 635699/0; "Buffering" = 73.01
05:36:15.053 T:18446744071693306144  NOTICE: [plugin.video.elementum] accepted connection from 43.243.83.5:45832
05:36:15.078 T:18446744071693306144  NOTICE: [plugin.video.elementum] DEBU  torrent      ▶ progressEvent    PR: 635699/0; "Buffering" = 73.14
05:36:15.449 T:18446744071693306144  NOTICE: [plugin.video.elementum] DEBU  torrent      ▶ progressEvent    PR: 652083/0; "Buffering" = 73.38
05:36:17.223 T:18446744071693306144  NOTICE: [plugin.video.elementum] accepted connection from 192.168.100.2:6888
05:36:17.266 T:18446744071693306144  NOTICE: [plugin.video.elementum] error establishing outgoing connection: error while establishing secret: EOF
05:36:17.279 T:18446744071693306144  NOTICE: Previous line repeats 1 times.
05:36:17.690 T:18446744072300263712   DEBUG: ------ Window Deinit (DialogExtendedProgressBar.xml) ------
05:36:17.708 T:18446744071693306144  NOTICE: [plugin.video.elementum] error receiving handshakes: UTP_ECONNRESET
05:36:17.712 T:18446744071693306144  NOTICE: [plugin.video.elementum] DEBU  torrent      ▶ progressEvent    PR: 825753/0; "Buffering" = 73.75
05:36:18.366 T:18446744071693306144  NOTICE: [plugin.video.elementum] DEBU  torrent      ▶ progressEvent    PR: 711065/0; "Buffering" = 73.89
05:36:18.407 T:18446744071693306144  NOTICE: [plugin.video.elementum] accepted connection from 86.41.249.184:24203
05:36:18.446 T:18446744071693306144  NOTICE: [plugin.video.elementum] accepted connection from 42.61.149.101:18868
05:36:18.456 T:18446744071693306144  NOTICE: [plugin.video.elementum] DEBU  torrent      ▶ progressEvent    PR: 711065/0; "Buffering" = 73.99
05:36:19.096 T:18446744071693306144  NOTICE: [plugin.video.elementum] accepted connection from 31.208.21.139:57803
05:36:19.844 T:18446744071693306144  NOTICE: [plugin.video.elementum] accepted connection from 189.10.37.157:1027
05:36:19.935 T:18446744071693306144  NOTICE: [plugin.video.elementum] accepted connection from 93.173.55.139:63437
05:36:19.956 T:18446744071718304032   ERROR: [plugin.video.elementum] Traceback (most recent call last):
05:36:19.960 T:18446744071718304032   ERROR: [plugin.video.elementum]   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/navigation.py", line 184, in run
05:36:19.969 T:18446744071718304032   ERROR: [plugin.video.elementum]     data = _json(url)
05:36:19.971 T:18446744071718304032   ERROR: [plugin.video.elementum]   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/navigation.py", line 127, in _json
05:36:19.986 T:18446744071718304032   ERROR: [plugin.video.elementum]     with closing(urllib2.urlopen(url)) as response:
05:36:19.996 T:18446744071718304032   ERROR: [plugin.video.elementum]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 154, in urlopen
05:36:20.002 T:18446744071718304032   ERROR: [plugin.video.elementum]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 429, in open
05:36:20.008 T:18446744071718304032   ERROR: [plugin.video.elementum]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 447, in _open
05:36:20.035 T:18446744071718304032   ERROR: [plugin.video.elementum]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 407, in _call_chain
05:36:20.036 T:18446744071718304032   ERROR: [plugin.video.elementum]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 1228, in http_open
05:36:20.042 T:18446744071718304032   ERROR: [plugin.video.elementum]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 1201, in do_open
05:36:20.044 T:18446744071718304032   ERROR: [plugin.video.elementum]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/httplib.py", line 1136, in getresponse
05:36:20.045 T:18446744071718304032   ERROR: [plugin.video.elementum]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/httplib.py", line 453, in begin
05:36:20.047 T:18446744071718304032   ERROR: [plugin.video.elementum]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/httplib.py", line 409, in _read_status
05:36:20.054 T:18446744071718304032   ERROR: [plugin.video.elementum]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/socket.py", line 480, in readline
05:36:20.061 T:18446744071718304032   ERROR: [plugin.video.elementum] timeout: timed out
05:36:20.062 T:18446744071718304032   ERROR: [plugin.video.elementum]
05:36:20.078 T:18446744072300263712   DEBUG: ------ Window Init (DialogNotification.xml) ------
05:36:20.080 T:18446744071693306144  NOTICE: [plugin.video.elementum] DEBU  torrent      ▶ progressEvent    PR: 760217/0; "Buffering" = 74.31
05:36:20.102 T:18446744071718304032    INFO: CPythonInvoker(16, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/navigation.py): script successfully run
05:36:20.278 T:18446744071718304032    INFO: Python script stopped
05:36:20.282 T:18446744071718304032   DEBUG: Thread LanguageInvoker 18446744071718304032 terminating
05:36:20.291 T:18446744071637043488   DEBUG: Thread scriptobs 18446744071637043488 terminating
05:36:20.324 T:18446744072300263712   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.elementum/show/1418/season/11/episode/5/links]
05:36:20.326 T:18446744072300263712   DEBUG: Playlist Player: one or more items failed to play... aborting playback
05:36:20.328 T:18446744072300263712   DEBUG: ------ Window Init (DialogConfirm.xml) ------
05:36:20.329 T:18446744072300263712    INFO: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
05:36:20.562 T:18446744072300263712   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
05:36:20.747 T:18446744071693306144  NOTICE: [plugin.video.elementum] DEBU  torrent      ▶ progressEvent    PR: 553779/0; "Buffering" = 74.49
```

The errors specifically.

Also I struggle to understand why it's referring to paths from Jenkins. Maybe that's what causing it? Anyway, I'll try and install the latest version and report back.

**Comment by elgatito** [comment]
Jenkins path is a virtual path used by Kodi's Python, don't take it in mind.
Your buffer is still downloading at that time. Again, it's not the end of torrent processing.

**Comment by hoshsadiq** [comment]
Same thing. It's getting late, I will post a new log tomorrow.

**Comment by hoshsadiq** [comment]
Weirdly, just now, I tried again after enabling debug mode, and it suddenly works. I've no idea what's going on! But no worries. Thanks

**Comment by elgatito** [comment]
There were changes to Android Arm/Arm64 detection, which caused some problems, so it could be related somehow.
