### ISSUE TITLE
searching anime

### ISSUE THREAD

**Issue by ramonskie** [elgatito/plugin.video.elementum#257]
when selecting an anime episode it fails with the following error

```
18:09:28.623 T:544889557216  NOTICE: [plugin.video.elementum] INFO  api          ▶ showEpisodeLinks  Searching links for TMDB Id: 30984
18:09:28.630 T:544889557216  NOTICE: [plugin.video.elementum]
18:09:28.631 T:544889557216  NOTICE: Previous line repeats 1 times.
18:09:28.631 T:544889557216  NOTICE: [plugin.video.elementum] 2018/10/01 16:09:28 [Recovery] 2018/10/01 - 16:09:28 panic recovered:
18:09:28.631 T:544889557216  NOTICE: [plugin.video.elementum] GET /show/30984/season/16/episode/343/links HTTP/1.1
18:09:28.631 T:544889557216  NOTICE: [plugin.video.elementum] Host: 127.0.0.1:65220
18:09:28.631 T:544889557216  NOTICE: [plugin.video.elementum] Connection: close
18:09:28.632 T:544889557216  NOTICE: [plugin.video.elementum] Accept-Encoding: identity
18:09:28.632 T:544889557216  NOTICE: [plugin.video.elementum] Connection: close
18:09:28.632 T:544889557216  NOTICE: [plugin.video.elementum] User-Agent: Python-urllib/2.7
18:09:28.632 T:544889557216  NOTICE: [plugin.video.elementum]
18:09:28.633 T:544889557216  NOTICE: Previous line repeats 1 times.
18:09:28.633 T:544889557216  NOTICE: [plugin.video.elementum] runtime error: index out of range
18:09:28.633 T:544889557216  NOTICE: [plugin.video.elementum] /usr/local/go/src/runtime/panic.go:502 (0x43588f)
18:09:28.633 T:544889557216  NOTICE: [plugin.video.elementum] /usr/local/go/src/runtime/panic.go:28 (0x434723)
18:09:28.633 T:544889557216  NOTICE: [plugin.video.elementum] /ext-go/1/src/github.com/elgatito/elementum/api/shows.go:642 (0xc3d51b)
18:09:28.634 T:544889557216  NOTICE: [plugin.video.elementum] /ext-go/1/src/github.com/elgatito/elementum/api/shows.go:735 (0xc50d2f)
18:09:28.634 T:544889557216  NOTICE: [plugin.video.elementum] /ext-go/2/src/github.com/gin-gonic/gin/context.go:108 (0x8bb4b3)
18:09:28.634 T:544889557216  NOTICE: [plugin.video.elementum] /ext-go/2/src/github.com/gin-gonic/gin/logger.go:84 (0x8c91ab)
18:09:28.634 T:544889557216  NOTICE: [plugin.video.elementum] /ext-go/2/src/github.com/gin-gonic/gin/context.go:108 (0x8bb4b3)
18:09:28.635 T:544889557216  NOTICE: [plugin.video.elementum] /ext-go/2/src/github.com/gin-gonic/gin/recovery.go:48 (0x8c9d1f)
18:09:28.635 T:544889557216  NOTICE: [plugin.video.elementum] /ext-go/2/src/github.com/gin-gonic/gin/context.go:108 (0x8bb4b3)
18:09:28.635 T:544889557216  NOTICE: [plugin.video.elementum] /ext-go/2/src/github.com/gin-gonic/gin/gin.go:361 (0x8c238f)
18:09:28.635 T:544889557216  NOTICE: [plugin.video.elementum] /ext-go/2/src/github.com/gin-gonic/gin/gin.go:326 (0x8c1ce3)
18:09:28.636 T:544889557216  NOTICE: [plugin.video.elementum] /usr/local/go/src/net/http/server.go:2337 (0x651eaf)
18:09:28.636 T:544889557216  NOTICE: [plugin.video.elementum] /usr/local/go/src/net/http/server.go:2694 (0x652d93)
18:09:28.636 T:544889557216  NOTICE: [plugin.video.elementum] /usr/local/go/src/net/http/server.go:1830 (0x64f837)
18:09:28.636 T:544889557216  NOTICE: [plugin.video.elementum] /usr/local/go/src/runtime/asm_arm64.s:1037 (0x461df3)
18:09:28.637 T:544889557216  NOTICE: [plugin.video.elementum] 
18:09:28.641 T:544791171296   ERROR: [plugin.video.elementum] Traceback (most recent call last):
18:09:28.641 T:544791171296   ERROR: [plugin.video.elementum]   File "/storage/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/navigation.py", line 176, in run
18:09:28.641 T:544791171296   ERROR: [plugin.video.elementum]     data = _json(url)
18:09:28.641 T:544791171296   ERROR: [plugin.video.elementum]   File "/storage/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/navigation.py", line 131, in _json
18:09:28.642 T:544791171296   ERROR: [plugin.video.elementum]     with closing(urllib2.urlopen(url)) as response:
18:09:28.642 T:544791171296   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
18:09:28.642 T:544791171296   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 435, in open
18:09:28.642 T:544791171296   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
18:09:28.642 T:544791171296   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 473, in error
18:09:28.642 T:544791171296   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
18:09:28.642 T:544791171296   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
18:09:28.643 T:544791171296   ERROR: [plugin.video.elementum] HTTPError: HTTP Error 500: Internal Server Error
18:09:28.643 T:544791171296   ERROR: [plugin.video.elementum]
18:09:28.816 T:547532558336   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.elementum/show/30984/season/16/episode/343/links]
```

## Steps to Reproduce (for bugs)
1. open elementum
2. select tv shows
3. search (any anime series)
4. select an episode.
5. internal error is shown on screen.

running on latest stable libreelec.
cubox i4

**Comment by elgatito** [comment]
Will be fixed in the next version.
