### ISSUE TITLE
[Bug] Error notification when kodi start and Elementum is up

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#278]
## Bug
Error notification when kodi start and Elementum is up.
It wasn't before 0.0.63 update

Basically I have a widget which point to one of Trakt menus in Elementum, so maybe it's timing issue, but it wasn't before the last update of 0.0.63

## Your Environment
* Version used: 0.0.63
* Kodi 17.6
* Windows 10 , 64bit
* Link to Kodi debug log: https://paste.ubuntu.com/p/FCH6prpFh7/
* Second log: https://paste.ubuntu.com/p/gFHyQ8cG5Y/

I think you should focus on this:
```
17:55:16.776 T:4400   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: argument "message" for method "notification" must be unicode or str
                                            Traceback (most recent call last):
                                              File "C:\Users\aUser\AppData\Roaming\Kodi\addons\plugin.video.elementum\navigation.py", line 6, in <module>
                                                navigation.run()
                                              File "C:\Users\aUser\AppData\Roaming\Kodi\addons\plugin.video.elementum\resources\site-packages\elementum\navigation.py", line 190, in run
                                                notify(e.reason, time=7000)
                                              File "C:\Users\aUser\AppData\Roaming\Kodi\addons\plugin.video.elementum\resources\site-packages\elementum\util.py", line 13, in notify
                                                return dialog.notification(toUtf8(header), toUtf8(message), toUtf8(image), time, sound)
                                            TypeError: argument "message" for method "notification" must be unicode or str
                                            -->End of Python script error report<--
17:55:19.291 T:6152   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.elementum/shows/trakt/progress?reload=
```

**Comment by elgatito** [comment]
```

17:55:15.424 T:4400   ERROR: [plugin.video.elementum] URLError: <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>

```

You are requesting plugin before it's loaded. So you get errors.

**Comment by elgatito** [comment]
In last versions Elementum was modified to start faster, but anyway, it's controlled by Kodi - who and when starts first.
