### ISSUE TITLE
burst does not work with proxy enabled when server run separately

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#304]
## Current Behavior

nothing found and in my linux pc console I see (kodi's log is below)
```
INFO  bittorrent   ▶ configure        Client created successfully
DEBU  bittorrent   ▶ configure        Client listening on tcp: 0.0.0.0:52789
DEBU  bittorrent   ▶ configure        Client listening on tcp: [::]:52789
DEBU  bittorrent   ▶ configure        Client listening on udp: 0.0.0.0:52789
DEBU  bittorrent   ▶ configure        Client listening on udp: [::]:52789
INFO  main         ▶ Discover         UPnP discovery result 00e0fc37-2525-2828-2500-4482E5C02DB1/WANDevice/urn:upnp-org:serviceId:WANIPConn1/urn:schemas-upnp-org:service:WANIPConnection:1/http://192.168.0.1:49652/upnp/control/WANIPConn1
[GIN] 2018/12/20 - 00:00:30 | 200 |  1.102756894s |   192.168.0.115 | GET      /cmd/clear_page_cache
2018-12-20 00:00:31 portfwd.go:31: discovered 1 upnp devices
2018/12/20 00:00:31 error adding UDP port mapping: AddPortMapping: 500 Internal Server Error
2018/12/20 00:00:31 error adding TCP port mapping: AddPortMapping: 500 Internal Server Error
DEBU  main         ▶ Notification     Got notification from xbmc/System.OnQuit: {"exitcode":0}
2018-12-20 00:00:44 client.go:324: dht server on [::]:52789: dht bootstrap: dht.TraversalStats{NumAddrsTried:9, NumResponses:0}
[GIN] 2018/12/20 - 00:00:54 | 200 |     131.997µs |   192.168.0.115 | GET      /?reload=
[GIN] 2018/12/20 - 00:00:59 | 200 |     133.095µs |   192.168.0.115 | GET      /
[GIN] 2018/12/20 - 00:01:02 | 200 |     322.742µs |   192.168.0.115 | GET      /search
INFO  search       ▶ func1            Searching providers for: Supernatural s14e09
INFO  linkssearch  ▶ processLinks     Resolving torrent files...
[GIN] 2018/12/20 - 00:01:07 | 200 |      31.393µs |   192.168.0.115 | POST     /callbacks/8493126795071569868
[GIN] 2018/12/20 - 00:01:09 | 200 |      17.404µs |   192.168.0.115 | POST     /callbacks/3008148350171177557
INFO  linkssearch  ▶ processLinks     Received 0 unique links.
DEBU  linkssearch  ▶ func1            Closing progressupdate
[GIN] 2018/12/20 - 00:01:10 | 200 |  5.560344842s |   192.168.0.115 | GET      /search?q=Supernatural%!s(MISSING)14e09
[GIN] 2018/12/20 - 00:01:11 | 200 |     289.411µs |   192.168.0.115 | GET      /search
```

## Steps to Reproduce (for bugs)

1. run server on separate host
2. enable proxy in burst
3. search something
4.

## Your Environment

* Version used: 0.68

* Environment name and version: kodi 18

* Operating System and version: android 8 + linux

* Link to Kodi debug log:

https://paste.ubuntu.com/p/T8qVwtjmHc/

**Comment by antonsoroko** [comment]
also when server is run on arm linux device with proxy enabled I have a lot of timeouts in even nova provider and then
```
2018-12-21 05:44:03 client.go:324: dht server on 0.0.0.0:33485: dht bootstrap: dht.TraversalStats{NumAddrsTried:9236, NumResponses:5975}
panic: sync: negative WaitGroup counter

goroutine 66531 [running]:
sync.(*WaitGroup).Add(0x2d2b9a0, 0xffffffff)
	/usr/local/go/src/sync/waitgroup.go:74 +0x158
sync.(*WaitGroup).Done(0x2d2b9a0)
	/usr/local/go/src/sync/waitgroup.go:99 +0x24
github.com/anacrolix/dht.(*Server).Bootstrap.func1.1(0x0, 0x0, 0x0, 0x2f62b12, 0x2, 0x2f62b1d, 0x1, 0x39b2740, 0x0, 0x2f62a20, ...)
	/ext-go/2/src/github.com/anacrolix/dht/server.go:723 +0xb4
github.com/anacrolix/dht.(*Server).findNode.func1(0x0, 0x0, 0x0, 0x2f62b12, 0x2, 0x2f62b1d, 0x1, 0x39b2740, 0x0, 0x2f62a20, ...)
	/ext-go/2/src/github.com/anacrolix/dht/server.go:685 +0x80
created by github.com/anacrolix/dht.(*Server).query.func3
	/ext-go/2/src/github.com/anacrolix/dht/server.go:594 +0x50
```

**Comment by elgatito** [comment]
@antonsoroko any panic, raised by torrent library should be reported to it's repository - https://github.com/anacrolix/torrent/issues

**Comment by antonsoroko** [comment]
Okay. Will do. Thanks.

Anyway initial issue stays the same.

**Comment by antonsoroko** [comment]
Btw, this panic appears only when proxy is enabled

**Comment by antonsoroko** [comment]
sorry to say, but no luck with 0.0.70:
```
[GIN] 2018/12/28 - 00:37:47 | 200 |    22.11945ms |   192.168.0.115 | GET      /search
INFO  search       ▶ func1            Searching providers for: Гоголь страшная месть
INFO  linkssearch  ▶ processLinks     Resolving torrent files...
2018-12-28 00:37:53 client.go:324: dht server on [::]:49700: dht bootstrap: dht.TraversalStats{NumAddrsTried:9, NumResponses:0}
WARN  AddonSearcher script.elementum.burst ▶ call             Provider script.elementum.burst was too slow. Ignored.
WARN  AddonSearcher script.elementum.nova ▶ call             Provider script.elementum.nova was too slow. Ignored.
INFO  linkssearch  ▶ processLinks     Received 0 unique links.
DEBU  linkssearch  ▶ func1            Closing progressupdate
[GIN] 2018/12/28 - 00:38:33 | 200 | 43.603027951s |   192.168.0.115 | GET      /search?q=%!d(MISSING)0%d0%!b(MISSING)e%!d(MISSING)0%!b(MISSING)3%!d(MISSING)0%!b(MISSING)e%!d(MISSING)0%!b(MISSING)b%!d(MISSING)1%!c(MISSING)%d1%d1%d1%d0%!b(MISSING)0%!d(MISSING)1%d0%!b(MISSING)d%!d(MISSING)0%!b(MISSING)0%!d(MISSING)1%!f(MISSING)%d0%!b(MISSING)c%!d(MISSING)0%!b(MISSING)5%!d(MISSING)1%d1%d1%!c(MISSING)
[GIN] 2018/12/28 - 00:38:34 | 200 |     284.895µs |   192.168.0.115 | GET      /search
```
```
INFO  search       ▶ func1            Searching providers for: Supernatural s14e09
INFO  linkssearch  ▶ processLinks     Resolving torrent files...
WARN  AddonSearcher script.elementum.nova ▶ call             Provider script.elementum.nova was too slow. Ignored.
WARN  AddonSearcher script.elementum.burst ▶ call             Provider script.elementum.burst was too slow. Ignored.
INFO  linkssearch  ▶ processLinks     Received 0 unique links.
DEBU  linkssearch  ▶ func1            Closing progressupdate
[GIN] 2018/12/28 - 00:39:42 | 200 | 40.509918171s |   192.168.0.115 | GET      /search?q=Supernatural%!s(MISSING)14e09
[GIN] 2018/12/28 - 00:39:43 | 200 |     292.951µs |   192.168.0.115 | GET      /search
```

**Comment by elgatito** [comment]
Full log!

**Comment by antonsoroko** [comment]
@elgatito 
server side https://paste.ubuntu.com/p/Q8VQvjKYwr/
client side https://paste.ubuntu.com/p/2rxSxBfqSK/

**Comment by antonsoroko** [comment]
что-то всё поломалось с момента 0.0.68
раньше при отключении использования прокси в бёрсте все работало
сейчас не работает ни бёрст, ни нова даже, хотя в логе я вижу что она что-то нашла

а если отключить хттп прокси в елементуме то отваливается и бёрст (в котором тоже отключено использование прокси) и нова (в котором нет вообще опции такой), они всё равно стучатся на :65222 зачем-то
но раньше можно было отключать хттп прокси в елементуме вроде как в 67 или 68

https://paste.ubuntu.com/p/7VzZnBQvNx/

**Comment by elgatito** [comment]
Это не баг. Я бы вообще вырезал все возможности запустить разделенно клиент/сервер. Больше проблем только. Коди ограниченная система с массой ограничений.

'internal_proxy_url' передается поисковикам, чтоб они могли найти прокси в локальной сети. Никак не связано с тем где слушает библиотека торрента.

**Comment by antonsoroko** [comment]
fixed, thx
