### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by hoshsadiq** [elgatito/plugin.video.elementum#39]
Every now and then I get a random crash. I have only the basic log as I have no way of reproducing it (since I don't know what steps cause it to crash). Seems to be an index out of range issue. Logs are [here](https://pastebin.com/NPCjQah4). 

```
22:53:48.674 T:18446744071702055200  NOTICE: [plugin.video.elementum] panic: runtime error: index out of range
22:53:48.675 T:18446744071702055200  NOTICE: [plugin.video.elementum]
22:53:48.676 T:18446744071702055200  NOTICE: [plugin.video.elementum] goroutine 9135 [running]:
22:53:48.677 T:18446744071702055200  NOTICE: [plugin.video.elementum] github.com/anacrolix/torrent.(*Torrent).piecePriority(...)
22:53:48.680 T:18446744071702055200  NOTICE: [plugin.video.elementum]   /ext-go/2/src/github.com/anacrolix/torrent/torrent.go:938
22:53:48.682 T:18446744071702055200  NOTICE: [plugin.video.elementum] github.com/anacrolix/torrent.(*connection).updatePiecePriority(0x89952960, 0xffffffff, 0x1)
22:53:48.683 T:18446744071702055200  NOTICE: [plugin.video.elementum]   /ext-go/2/src/github.com/anacrolix/torrent/connection.go:609 +0x1c0
22:53:48.686 T:18446744071702055200  NOTICE: [plugin.video.elementum] github.com/anacrolix/torrent.(*connection).peerSentHave(0x89952960, 0xffffffff, 0x1, 0x1)
22:53:48.688 T:18446744071702055200  NOTICE: [plugin.video.elementum]   /ext-go/2/src/github.com/anacrolix/torrent/connection.go:678 +0xa8
22:53:48.690 T:18446744071702055200  NOTICE: [plugin.video.elementum] github.com/anacrolix/torrent.(*connection).mainReadLoop(0x89952960, 0x89952960, 0x896f91e0)
22:53:48.691 T:18446744071702055200  NOTICE: [plugin.video.elementum]   /ext-go/2/src/github.com/anacrolix/torrent/connection.go:843 +0x320
22:53:48.694 T:18446744071702055200  NOTICE: [plugin.video.elementum] github.com/anacrolix/torrent.(*Client).runHandshookConn(0x89454480, 0x89952960, 0x896f91e0, 0x89a4ff01)
22:53:48.695 T:18446744071702055200  NOTICE: [plugin.video.elementum]   /ext-go/2/src/github.com/anacrolix/torrent/client.go:849 +0x190
22:53:48.697 T:18446744071702055200  NOTICE: [plugin.video.elementum] github.com/anacrolix/torrent.(*Client).runInitiatedHandshookConn(0x89454480, 0x89952960, 0x896f91e0)
22:53:48.698 T:18446744071702055200  NOTICE: [plugin.video.elementum]   /ext-go/2/src/github.com/anacrolix/torrent/client.go:809 +0xf4
22:53:48.700 T:18446744071702055200  NOTICE: [plugin.video.elementum] github.com/anacrolix/torrent.(*Client).outgoingConnection(0x89454480, 0x896f91e0, 0x89879680, 0x13, 0xa9fac112, 0x2)
22:53:48.701 T:18446744071702055200  NOTICE: [plugin.video.elementum]   /ext-go/2/src/github.com/anacrolix/torrent/client.go:700 +0x194
22:53:48.702 T:18446744071702055200  NOTICE: [plugin.video.elementum] created by github.com/anacrolix/torrent.(*Client).initiateConn
22:53:48.704 T:18446744071702055200  NOTICE: [plugin.video.elementum]   /ext-go/2/src/github.com/anacrolix/torrent/client.go:519 +0x1f0
```

Also the following trace is there:
```
22:53:48.765 T:18446744071813724448   ERROR: [plugin.video.elementum] Traceback (most recent call last):
22:53:48.766 T:18446744071813724448   ERROR: [plugin.video.elementum]   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/navigation.py", line 184, in run
22:53:48.767 T:18446744071813724448   ERROR: [plugin.video.elementum]     data = _json(url)
22:53:48.768 T:18446744071813724448   ERROR: [plugin.video.elementum]   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/navigation.py", line 127, in _json
22:53:48.769 T:18446744071813724448   ERROR: [plugin.video.elementum]     with closing(urllib2.urlopen(url)) as response:
22:53:48.770 T:18446744071813724448   ERROR: [plugin.video.elementum]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 154, in urlopen
22:53:48.770 T:18446744071813724448   ERROR: [plugin.video.elementum]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 429, in open
22:53:48.771 T:18446744071813724448   ERROR: [plugin.video.elementum]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 447, in _open
22:53:48.771 T:18446744071813724448   ERROR: [plugin.video.elementum]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 407, in _call_chain
22:53:48.772 T:18446744071813724448   ERROR: [plugin.video.elementum]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 1228, in http_open
22:53:48.772 T:18446744071813724448   ERROR: [plugin.video.elementum]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 1201, in do_open
22:53:48.773 T:18446744071813724448   ERROR: [plugin.video.elementum]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/httplib.py", line 1136, in getresponse
22:53:48.774 T:18446744071813724448   ERROR: [plugin.video.elementum]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/httplib.py", line 453, in begin
22:53:48.774 T:18446744071813724448   ERROR: [plugin.video.elementum]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/httplib.py", line 417, in _read_status
22:53:48.777 T:18446744071813724448   ERROR: [plugin.video.elementum] BadStatusLine: ''
22:53:48.778 T:18446744071813724448   ERROR: [plugin.video.elementum]
22:53:48.953 T:18446744072242067744   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.elementum/search?q=Family+Guy+S16E10]
```

Some other errors too. I can't give you a debug log like I said as it happens randomly and I have no idea what's causing it.

Lastly, seems my system still isn't detected correct:
```
platform: Could not detect
```

So you're aware, I'm running Android TV. The CPU is capable of x64, but I think the OS is actually x86. See below the build properties:
```
BRAVIA_ATV2:/ $ cat /system/build.prop
# begin build properties
# autogenerated by buildinfo.sh
ro.build.id=NRD91N.S90
ro.build.display.id=BRAVIA_ATV2_EU-user 7.0 NRD91N.S90 1.6.0.26.71.1.00 release-keys
ro.build.version.incremental=1.6.0.26.71.1.00
ro.build.version.sdk=24
ro.build.version.preview_sdk=0
ro.build.version.codename=REL
ro.build.version.all_codenames=REL
ro.build.version.release=7.0
ro.build.version.security_patch=2017-08-01
ro.build.version.base_os=
ro.build.date=Wed Oct  4 18:14:42 JST 2017
ro.build.date.utc=1507108482
ro.build.type=user
ro.build.user=root
ro.build.host=BuildHost538
ro.build.tags=release-keys
ro.build.flavor=Trinity_EU-user
ro.product.model=BRAVIA 4K GB
ro.product.brand=Sony
ro.product.name=BRAVIA_ATV2_EU
ro.product.device=BRAVIA_ATV2
ro.product.board=BRAVIA_ATV2
# ro.product.cpu.abi and ro.product.cpu.abi2 are obsolete,
# use ro.product.cpu.abilist instead.
ro.product.cpu.abi=armeabi-v7a
ro.product.cpu.abi2=armeabi
ro.product.cpu.abilist=armeabi-v7a,armeabi
ro.product.cpu.abilist32=armeabi-v7a,armeabi
ro.product.cpu.abilist64=
ro.product.manufacturer=Sony
ro.product.locale=en-GB
ro.wifi.channels=
ro.board.platform=mt5891
# ro.build.product is obsolete; use ro.product.device
ro.build.product=BRAVIA_ATV2
# Do not try to parse description, fingerprint, or thumbprint
ro.build.description=BRAVIA_ATV2_EU-user 7.0 NRD91N.S90 1.6.0.26.71.1.00 release-keys
ro.build.fingerprint=Sony/BRAVIA_ATV2_EU/BRAVIA_ATV2:7.0/NRD91N.S90/1.6.0.26.71.1.00:user/release-keys
ro.build.characteristics=nosdcard,tv
# end build properties

#
# ADDITIONAL_BUILD_PROPERTIES
#
net.dns1=8.8.8.8
net.dns2=8.8.4.4
wifi.interface=wlan0
ro.opengles.version=196610
ro.sf.lcd_density=320
ro.camera.hal32.support=1
ro.hdmi.device_type=0
persist.bt.avrcp.ct=0
sys.mtk.tvremoteservice.ready=0
ro.mtk.twoworlds=1
ro.mtk.sys_driver_only=0
dalvik.vm.heapsize=512m
dalvik.vm.heapgrowthlimit=192m
ro.hwui.disable_scissor_opt=true
ro.hwui.drop_shadow_cache_size=6
ro.hwui.gradient_cache_size=1
ro.hwui.layer_cache_size=48
ro.hwui.path_cache_size=32
ro.hwui.r_buffer_cache_size=8
ro.hwui.text_large_cache_height=1024
ro.hwui.text_large_cache_width=2048
ro.hwui.text_small_cache_height=1024
ro.hwui.text_small_cache_width=1024
ro.hwui.texture_cache_flushrate=0.4
ro.hwui.texture_cache_size=48
dalvik.vm.heapstartsize=16m
dalvik.vm.heaptargetutilization=0.75
dalvik.vm.heapminfree=512k
dalvik.vm.heapmaxfree=8m
ro.boot.flash.locked=1
ro.product.first_api_level=24
mtk.inside=1
ro.adb.secure=1
ro.config.media_vol_steps=100
mtk.omx.vdp=0
media.stagefright.codecremote=0
sys.display-size=3840x2160
sys.fw.alarmmanager=0
sys.fw.powermanager=0
mtk.wifi.driverinfo=1
media.aac_51_output_enabled=true
drm.service.enabled=true
ro.mtk.4k2k.photo=1
ro.mtk.disable_scrn_rt=1
mtk.browser.useCmpbPlayer=0
mtk.browser.alwaysFullscreen=0
mtk.browser.openLinkInSameTab=1
mtk.browser.freePlayerWhenPause=0
ro.mtk.pkg_version=t-apollo-dev-1501-1531-0-001-245-001-13-sony-t250-7-10
mtk.auto_test=0
ro.mtk.system.dmv=0
ro.mtk.camera.facingback=0
ro.mtk.system.tkui=0
use.cmpb.in.gallery=1
mtk.no_long_press_do_standby=1
mtk.pms.suspend_wait_timeout=10
mtk.screen.always.on=0
mtk.disable.screen.lock=1
mtk.tms_support=1
mtk.bgm_custom_flow=0
sys.mtk.keyDisable=0
persist.mtk.printk_level=0
persist.mtk.k2mlog=1
persist.logd.size.main=1M
persist.sys.strictmode.visual=0
persist.sys.strictmode.disable=1
ro.pm.warmboot=1
sys.pm.warmboot=1
sys.vold.autoflag=1
sys.pm.warmboot.flag=0
emulated.sdcard.dev=mmcblk0p47
persist.svp.dbg.psserver=0
persist.svp.dbg.pstore=0
persist.svp.dbg.irq_debug=0
persist.svp.dbg.copy2bugreport=0
persist.svp.dbg.sysrq=0
persist.sys.media.avsync=true
ro.camera.firmware.path=/system/vendor/firmware/quanta
ro.com.google.clientidbase=android-sony-tv
ro.setupwizard.mode=OPTIONAL
ro.com.google.gmsversion=N_Q1_2017_BUILD_3783102
persist.sys.dalvik.vm.lib.2=libart.so
dalvik.vm.isa.arm.variant=cortex-a9
dalvik.vm.isa.arm.features=default
net.bt.name=Android
dalvik.vm.stack-trace-file=/data/anr/traces.txt
ro.expect.recovery_id=<clipped>
```

Happy to give you other information if needed.

**Comment by elgatito** [comment]
First part of an issue is reported to the library repository.

Second part. 
`platform: Could not detect` this is fine for android.
Does it run on that device? If yes - that is a normal message, if no - you should create a separate issue and port full log, it can still be detection is wrong for some platforms.

**Comment by hoshsadiq** [comment]
Thank you. Yes, it usually works. I guess if the main issue is fixed then we can close this.
