### ISSUE TITLE
Elementum crashes on startup on retropie kodi app

### ISSUE THREAD

**Issue by lpuglia** [elgatito/plugin.video.elementum#415]
## Expected Behavior
Elementum should be starting.

## Current Behavior
Elementum crashes after install (popup saying "Elementum has crashed, restarting..." on a loop until it gives up).

## Steps to Reproduce (for bugs)
- Install Retropie 4.3.13
- Install latest Kodi compatible version:

```
    10:09:47.868 T:1946182304  NOTICE: Starting Kodi (17.3 Git:20170525-1789806-dirty). Platform: Linux ARM 32-bit
    10:09:47.868 T:1946182304  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
    10:09:47.868 T:1946182304  NOTICE: Kodi compiled May 25 2017 by GCC 4.9.2 for Linux ARM 32-bit version 3.16.7 (200711)
    10:09:47.869 T:1946182304  NOTICE: Running on Raspbian GNU/Linux 8 (jessie), kernel: Linux ARM 32-bit version 4.9.35-v7+
```
- Install latest Elementum from [http://elementum.surge.sh/](here)

## Log
[https://paste.kodi.tv/palijeyuxe.kodi](https://paste.kodi.tv/palijeyuxe.kodi)

## Additional Information
Both remote control settings have been enabled.

I was able to run Elementum on a separate SD card with OSMC. Since i don't want to continuously switch between the two SD cards and all my favorite settings are on the Retropie one, i would like to know how to fix the crashes. 

The problem was already mentioned #313,  but unfortunately setting the path for the download and library folders doesn't solve the problem, any known incompatibility with any of my components?

**Comment by elgatito** [comment]
You can try to run manually from shell: `/home/pi/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7/elementum` , you will see the error.

**Comment by lpuglia** [comment]
The error i got was:
```
/usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/pi/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7/elementum)
```
my distro (and consequently `gcc`) was too old, I tried an update:
```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
```
but it didn't installed `gcc5` (which solved the problem), so i manually updated my repo list:
- `sudo nano /etc/apt/sources.list`
- Replace `jessie` with `stretch`

and then again:
```
sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get install gcc-5
sudo reboot
```

this fixed gcc problem:
```
pi@retropie:~ $ /home/pi/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7/elementum
INFO  main         ▶ main             Starting Elementum daemon
INFO  main         ▶ main             Version: 0.1.25 LibTorrent: 1.1.12.0 Go: go1.12, Threads: 4
INFO  config       ▶ Reload           Reloading configuration...
INFO  config       ▶ Reload           Setting remote address to 127.0.0.1:65221
WARN  config       ▶ Reload           Can't continue because addon info is empty
WARN  config       ▶ func1            Addon settings not properly set, opening settings window: "LOCALIZE[30113]"
```

At this point i got a message on Kodi:

```
Your version 0.6.1 of the Python cryptography module is too old. You need at least version 1.7. Please, upgrade your operating system. For more information, see https://kodi.wiki/view/linux
```

this thread explains how to solve it:
https://www.reddit.com/r/kodi/comments/9z2ekb/update_python_cryptography_kodi_on_retropie/

at the moment burst doesn't work (i suspect because of this last update), here is what i get in the log:

````
16:39:42.137 T:1441469360   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'SSL_ST_INIT'
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/script.elementum.burst/burst.py", line 7, in <module>
                                                from burst.burst import search
                                              File "/home/pi/.kodi/addons/script.elementum.burst/burst/burst.py", line 20, in <module>
                                                from provider import process
                                              File "/home/pi/.kodi/addons/script.elementum.burst/burst/provider.py", line 13, in <module>
                                                from client import Client
                                              File "/home/pi/.kodi/addons/script.elementum.burst/burst/client.py", line 11, in <module>
                                                import requests
                                              File "/home/pi/.kodi/addons/script.elementum.burst/resources/site-packages/requests/__init__.py", line 95, in <module>
                                                from urllib3.contrib import pyopenssl
                                              File "/home/pi/.kodi/addons/script.elementum.burst/resources/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
                                                import OpenSSL.SSL
                                              File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
                                                from OpenSSL import rand, crypto, SSL
                                              File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 105, in <module>
                                                SSL_ST_INIT = _lib.SSL_ST_INIT
                                            AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
                                            -->End of Python script error report<--
```

**Comment by lpuglia** [comment]
Ok, i solved the previous error with:
`sudo python -m easy_install --upgrade pyOpenSSL`

but provider do not respond: [https://paste.kodi.tv/cilogepuxu.kodi](https://paste.kodi.tv/cilogepuxu.kodi)

this is weird since the same provider on the OSMC sd card works good, i think it is related with pyopenssl, any suggestion?

**Comment by lpuglia** [comment]
finally solved the problem, i had to switch off the following setting in Burst:

`proxy https requests with elementum`

If this is NOT an important setting to turn off you can just close the issue.

**Comment by elgatito** [comment]
Proxying through Elementum gives ability to bypass Cloudflare defense (if you meet one). If you don't care - it's fine if you disable it.

**Comment by lpuglia** [comment]
No idea what Cloudflare is, closing for the moment.
