### ISSUE TITLE
Playing anything Elementum reports HTTP Error 500: Internal Server Error

### ISSUE THREAD

**Issue by limones1319** [elgatito/plugin.video.elementum#457]
Choosing anything to play, ends up reporting "Internal Server Error". Checking the logs it shows:

2019-06-23 11:27:09.263 T:1555157728  NOTICE: [plugin.video.elementum] 2019/06/23 08:27:09 [Recovery] 2019/06/23 - 08:27:09 panic recovered:
2019-06-23 11:27:09.264 T:1555157728  NOTICE: [plugin.video.elementum] page 767 already freed
2019-06-23 11:27:09.265 T:1555157728  NOTICE: [plugin.video.elementum] /go/src/github.com/boltdb/bolt/freelist.go:121 (0x53a1ef)
2019-06-23 11:27:09.265 T:1555157728  NOTICE: [plugin.video.elementum] /go/src/github.com/boltdb/bolt/node.go:363 (0x53c863)
2019-06-23 11:27:09.266 T:1555157728  NOTICE: [plugin.video.elementum] /go/src/github.com/boltdb/bolt/bucket.go:570 (0x533acb)
2019-06-23 11:27:09.267 T:1555157728  NOTICE: [plugin.video.elementum] /go/src/github.com/boltdb/bolt/bucket.go:537 (0x533a43)
2019-06-23 11:27:09.268 T:1555157728  NOTICE: [plugin.video.elementum] /go/src/github.com/boltdb/bolt/tx.go:163 (0x53efd7)
2019-06-23 11:27:09.268 T:1555157728  NOTICE: [plugin.video.elementum] /go/src/github.com/boltdb/bolt/db.go:605 (0x538397)
2019-06-23 11:27:09.269 T:1555157728  NOTICE: [plugin.video.elementum] /go/src/github.com/elgatito/elementum/database/bolt.go:434 (0x5f6aaf)
2019-06-23 11:27:09.270 T:1555157728  NOTICE: [plugin.video.elementum] /go/src/github.com/elgatito/elementum/database/bolt.go:449 (0x5f6bff)
2019-06-23 11:27:09.270 T:1555157728  NOTICE: [plugin.video.elementum] /go/src/github.com/elgatito/elementum/api/torrents.go:160 (0x97252f)
2019-06-23 11:27:09.272 T:1515975392   ERROR: [plugin.video.elementum] Traceback (most recent call last):
2019-06-23 11:27:09.272 T:1515975392   ERROR: [plugin.video.elementum]   File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/navigation.py", line 256, in run
2019-06-23 11:27:09.272 T:1515975392   ERROR: [plugin.video.elementum]     data = _json(url)
2019-06-23 11:27:09.273 T:1515975392   ERROR: [plugin.video.elementum]   File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/navigation.py", line 138, in _json
2019-06-23 11:27:09.273 T:1515975392   ERROR: [plugin.video.elementum]     with closing(urllib2.urlopen(url)) as response:
2019-06-23 11:27:09.274 T:1515975392   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
2019-06-23 11:27:09.274 T:1515975392   ERROR: [plugin.video.elementum]     return opener.open(url, data, timeout)
2019-06-23 11:27:09.274 T:1515975392   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 435, in open
2019-06-23 11:27:09.275 T:1515975392   ERROR: [plugin.video.elementum]     response = meth(req, response)
2019-06-23 11:27:09.275 T:1515975392   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
2019-06-23 11:27:09.276 T:1515975392   ERROR: [plugin.video.elementum]     'http', request, response, code, msg, hdrs)
2019-06-23 11:27:09.276 T:1515975392   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 473, in error
2019-06-23 11:27:09.277 T:1515975392   ERROR: [plugin.video.elementum]     return self._call_chain(*args)
2019-06-23 11:27:09.277 T:1515975392   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
2019-06-23 11:27:09.277 T:1515975392   ERROR: [plugin.video.elementum]     result = func(*args)
2019-06-23 11:27:09.278 T:1515975392   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
2019-06-23 11:27:09.278 T:1515975392   ERROR: [plugin.video.elementum]     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
2019-06-23 11:27:09.278 T:1515975392   ERROR: [plugin.video.elementum] HTTPError: HTTP Error 500: Internal Server Error
2019-06-23 11:27:09.279 T:1515975392   ERROR: [plugin.video.elementum]
2019-06-23 11:27:09.280 T:1555157728  NOTICE: [plugin.video.elementum] /go/src/github.com/elgatito/elementum/api/shows.go:802 (0x98ad37)
2019-06-23 11:27:09.433 T:1555157728  NOTICE: [plugin.video.elementum] /go/src/github.com/gin-gonic/gin/context.go:146 (0x4cd157)
2019-06-23 11:27:09.433 T:1555157728  NOTICE: [plugin.video.elementum] /go/src/github.com/gin-gonic/gin/logger.go:240 (0x4dd09f)
2019-06-23 11:27:09.434 T:1555157728  NOTICE: [plugin.video.elementum] /go/src/github.com/gin-gonic/gin/context.go:146 (0x4cd157)
2019-06-23 11:27:09.434 T:1555157728  NOTICE: [plugin.video.elementum] /go/src/github.com/gin-gonic/gin/recovery.go:83 (0x4ddcd7)
2019-06-23 11:27:09.435 T:1555157728  NOTICE: [plugin.video.elementum] /go/src/github.com/gin-gonic/gin/context.go:146 (0x4cd157)
2019-06-23 11:27:09.435 T:1555157728  NOTICE: [plugin.video.elementum] /go/src/github.com/gin-gonic/gin/gin.go:391 (0x4d54ff)
2019-06-23 11:27:09.436 T:1555157728  NOTICE: [plugin.video.elementum] /go/src/github.com/gin-gonic/gin/gin.go:352 (0x4d4dfb)
2019-06-23 11:27:09.436 T:1555157728  NOTICE: [plugin.video.elementum] /usr/local/go/src/net/http/server.go:2375 (0x2cab77)
2019-06-23 11:27:09.437 T:1555157728  NOTICE: [plugin.video.elementum] /usr/local/go/src/net/http/server.go:2774 (0x2cbc67)
2019-06-23 11:27:09.437 T:1555157728  NOTICE: [plugin.video.elementum] /usr/local/go/src/net/http/server.go:1878 (0x2c815b)
2019-06-23 11:27:09.437 T:1555157728  NOTICE: [plugin.video.elementum] /usr/local/go/src/runtime/asm_arm.s:868 (0x8819b)
2019-06-23 11:27:09.438 T:1555157728  NOTICE: [plugin.video.elementum]

## Expected Behavior
After selecting an episode, it should play the file, but instead it reports the above error. 

## Current Behavior
It searches the file using the providers, and immediately after reports the 500 error.

## Possible Solution
No solutions yet.

## Steps to Reproduce (for bugs)
1. Choosing anything to play, ends up reporting 500 error.

## Context
At he moment, the addon is unusable.

## Your Environment
* Version used:
version 0.1.35

* Environment name and version:
OSMC Kodi 18.3-RC1 

* Operating System and version:
OSMC

* Link to Kodi debug log:
https://paste.osmc.tv/alelasejof

**Comment by elgatito** [comment]
@limones1319 your database file is broken. Try to remove it manually `cache.db` and `library.db` files inside of Kodi's userdata folder.
