### ISSUE TITLE
[Request-Kodi 19] Добавить в библиотеке продолжение воспроизведение

### ISSUE THREAD

**Issue by Lontron** [elgatito/plugin.video.elementum#638]
В kodi 19 в библиотеке невозможно продолжить воспроизведение, но в kodi 18 работает. 
Если не сложно, можно также оставить структуру кода Python в комментарии, посмотрим что мы можем сделать.

![Screenshot (2)](https://user-images.githubusercontent.com/66425682/98874942-e074d180-2483-11eb-90b6-a38ae26aedc2.png)

**Comment by elgatito** [comment]
@Lontron debug log on kodi19?

**Comment by Lontron** [comment]
> @Lontron debug log on kodi19?


```
2020-11-12 13:07:27.259 T:7592  WARNING <general>: [plugin.video.elementum] b'INFO  bittorrent   \xe2\x96\xb6 playerLoop       Playback loop\n'
2020-11-12 13:07:27.271 T:1280     INFO <general>: Creating InputStream
2020-11-12 13:07:27.277 T:7592  WARNING <general>: [plugin.video.elementum] b'INFO  bittorrent   \xe2\x96\xb6 playerLoop       Got playback: 0.000000s / 0.000000s\n'
```

http://paste.kodi.tv/nirovomenu

**Comment by elgatito** [comment]
@vlmaksime есть возможность посмотреть?
У нас тут есть монитор, который пробрасывает все происшествия на вебсервер, но в логе я не вижу чтоб что-то приходило.
Возможно что-то поменяли в мониторе.

https://github.com/elgatito/plugin.video.elementum/blob/master/resources/site-packages/elementum/monitor.py#L42

**Comment by vlmaksime** [comment]
Скорей всего до монитора не дошло. В 19й версии были изменения в механизме запуска strm ссылок из библиотеки. Вроде как должно было браться время просмотра из библиотеки и использоваться при запуске.
Вечером постараюсь глянуть.

**Comment by elgatito** [comment]
@vlmaksime Не, там монитор сообщает если что-то запустилось, к примеру (в принципе что либо, хоть канал, хоть файл, хоть ютюб), в нашем случае интересует Player.*.
Там совсем не приходят нотификации от Коди.

**Comment by vlmaksime** [comment]
В монитор сообщение приходит. Проблема при попытке сформировать строку для запроса к elementum. 
`2020-11-15 17:13:28.140 T:9572    DEBUG <general>: <elementum.monitor.ElementumMonitor object at 0x000001973F695F90>.onNotification(xbmc, Playlist.OnRemove, {"playlistid":1,"position":0})
2020-11-15 17:13:28.140 T:9572    DEBUG <general>: 
                                                   
2020-11-15 17:13:28.143 T:9572    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: a bytes-like object is required, not 'str'
                                                   Traceback (most recent call last):
                                                     File "d:\KODI\Portable\kodi_19\portable_data\addons\plugin.video.elementum\resources\site-packages\elementum\monitor.py", line 49, in onNotification
                                                       base64.b64encode(data)))
                                                     File "d:\KODI\Portable\kodi_19\system\python\Lib\base64.py", line 58, in b64encode
                                                       encoded = binascii.b2a_base64(s, newline=False)
                                                   TypeError: a bytes-like object is required, not 'str'
                                                   -->End of Python script error report<--
`
Сейчас что-нибуть придумаю.

**Comment by elgatito** [comment]
@vlmaksime там должен быть человеческий utf8 на выходе, py_encode/decode попробовать может.
