### ISSUE TITLE
[BUG]Elementum does not work on Kodi Leia (18 alpha, neither Quasar)

### ISSUE THREAD

**Issue by mrdest** [elgatito/plugin.video.elementum#66]
1. Install nightly Leia build from http://mirrors.kodi.tv/nightlies/android/arm/master/
2. Install Elementum
3. Do the initial setup, and restart Kodi
Bug: 

> 23:21:17.623 T:18446744071694776624   ERROR: [plugin.video.elementum]     fp.seek(-40, os.SEEK_END)  # we put a sha1 there
23:21:17.624 T:18446744071694776624   ERROR: [plugin.video.elementum] IOError: [Errno 22] Invalid argument
23:21:17.624 T:18446744071694776624   ERROR: [plugin.video.elementum]
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 232, in elementumd_thread
                                                proc = start_elementumd(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 151, in start_elementumd
                                                elementum_dir, elementum_binary = get_elementum_binary()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 68, in get_elementum_binary
                                                if not os.path.exists(dest_binary_path) or not os.path.exists(binary_path) or get_elementumd_checksum(dest_binary_path) != get_elementumd_checksum(binary_path) or not filecmp.cmp(dest_binary_path, binary_path, shallow=True):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 29, in get_elementumd_checksum

**References**
/sdcard/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log
http://kodi.wiki/view/Kodi_v18_(Leia)_changelog - Has major changes for Android TV.

Tested on Nexus 7 2013, Android 6

**Comment by elgatito** [comment]
Have you tested on 18 Kodi with non-android system?

**Comment by mrdest** [comment]
No, too risky as I don't want to mess somehow my Library.

**Comment by herrwusel** [comment]
I'm running Kodi 18 (Libreelec 19 milhouse's builds) on Linux and Elementum is working fine. There are just some GUI error in settings but that's affecting also other plugins so it's not a Elementum issue I guess.

**Comment by elgatito** [comment]
Looks like something changed on android. I've got another one report of the same bug.

**Comment by elgatito** [comment]
Please, try the 0.0.33 and send the log.

**Comment by mrdest** [comment]
Thanks. I tried and got this exception:
> 12:56:55.096 T:18446744071663851824   ERROR: Exception in thread Thread-2:
                                            Traceback (most recent call last):
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-debug/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-debug/lib/python2.7/threading.py", line 754, in run
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 243, in elementumd_thread
                                                proc = start_elementumd(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 162, in start_elementumd
                                                elementum_dir, elementum_binary = get_elementum_binary()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 79, in get_elementum_binary
                                                if not os.path.exists(dest_binary_path) or not os.path.exists(binary_path) or get_elementumd_checksum(dest_binary_path) != get_elementumd_checksum(binary_path) or not filecmp.cmp(dest_binary_path, binary_path, shallow=True):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 36, in get_elementumd_checksum
                                                fp.seek(-40, os.SEEK_END)  # we put a sha1 there
                                            IOError: [Errno 22] Invalid argument

**Comment by elgatito** [comment]
Need more log, there are new messages, written in the log.

**Comment by mrdest** [comment]
Here:

> 12:59:13.682 T:18446744071934834992  NOTICE: [plugin.video.elementum] Detected binary folder: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/bin/android_arm
12:59:13.688 T:18446744071934834992  NOTICE: [plugin.video.elementum] Using changed binary folder for Android: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/bin/android_arm
12:59:13.729 T:18446744071934834992  NOTICE: [plugin.video.elementum] Source directory (/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/bin/android_arm):
                                            [u'android_arm', u'android_arm64', u'android_x86', u'darwin_x86', u'darwin_x64', u'ios_arm64', u'ios_arm-7', u'linux_arm-6', u'linux_arm-7', u'linux_arm64', u'linux_x64', u'linux_x86', u'windows_x64', u'windows_x86']
12:59:13.730 T:18446744071934834992  NOTICE: [plugin.video.elementum] Destination directory (/data/data/org.xbmc.kodi/files/plugin.video.elementum/bin/android_arm):
                                            ['android_arm']
12:59:13.731 T:18446744071934834992  NOTICE: [plugin.video.elementum] Binary detection. Source: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/bin/android_arm/elementum, Destination: /data/data/org.xbmc.kodi/files/plugin.video.elementum/bin/android_arm/elementum
12:59:13.837 T:18446744071934834992   ERROR: [plugin.video.elementum] Traceback (most recent call last):
12:59:13.838 T:18446744071934834992   ERROR: [plugin.video.elementum]   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 243, in elementumd_thread
12:59:13.839 T:18446744071934834992   ERROR: [plugin.video.elementum]     proc = start_elementumd(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
12:59:13.840 T:18446744071934834992   ERROR: [plugin.video.elementum]   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 162, in start_elementumd
12:59:13.841 T:18446744071934834992   ERROR: [plugin.video.elementum]     elementum_dir, elementum_binary = get_elementum_binary()
12:59:13.841 T:18446744071934834992   ERROR: [plugin.video.elementum]   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 79, in get_elementum_binary
12:59:13.842 T:18446744071934834992   ERROR: [plugin.video.elementum]     if not os.path.exists(dest_binary_path) or not os.path.exists(binary_path) or get_elementumd_checksum(dest_binary_path) != get_elementumd_checksum(binary_path) or not filecmp.cmp(dest_binary_path, binary_path, shallow=True):
12:59:13.843 T:18446744071934834992   ERROR: [plugin.video.elementum]   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 36, in get_elementumd_checksum
12:59:13.843 T:18446744071934834992   ERROR: [plugin.video.elementum]     fp.seek(-40, os.SEEK_END)  # we put a sha1 there
12:59:13.844 T:18446744071934834992   ERROR: [plugin.video.elementum] IOError: [Errno 22] Invalid argument
12:59:13.845 T:18446744071934834992   ERROR: [plugin.video.elementum]
12:59:13.869 T:18446744071934834992   ERROR: Exception in thread Thread-2:
                                            Traceback (most recent call last):
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-debug/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-debug/lib/python2.7/threading.py", line 754, in run
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 243, in elementumd_thread
                                                proc = start_elementumd(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 162, in start_elementumd
                                                elementum_dir, elementum_binary = get_elementum_binary()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 79, in get_elementum_binary
                                                if not os.path.exists(dest_binary_path) or not os.path.exists(binary_path) or get_elementumd_checksum(dest_binary_path) != get_elementumd_checksum(binary_path) or not filecmp.cmp(dest_binary_path, binary_path, shallow=True):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 36, in get_elementumd_checksum
                                                fp.seek(-40, os.SEEK_END)  # we put a sha1 there
                                            IOError: [Errno 22] Invalid argument

**Comment by elgatito** [comment]
I have updated the same 0.0.33, please, re-download and re-install it.

**Comment by mrdest** [comment]
Fixed!
