### ISSUE TITLE
Elementum has crashed, restarting

### ISSUE THREAD

**Issue by MedinaCat** [elgatito/plugin.video.elementum#803]
Log file: https://paste.kodi.tv/eyohafuvuk
Hello!
Hi! I have installed the Elementum add-on on Kodi 19.1 Matrix for Android Arm- 32 bits (Attached log file) The add-on does not start and it crashes What I can do? I have uninstalled Kodi and reinstalled it and I get the same error
Thanks for your attention!

**Comment by elgatito** [comment]
@MedinaCat You can try running manually from console, to verity the cause.

Also you can read this issue thread. https://github.com/elgatito/plugin.video.elementum/issues/669
Even though you are on Android 9, but you are on Google Nexus, so maybe there is some permissions issue.

**Comment by MedinaCat** [comment]
Thank you for answering me! I will take a look

**Comment by antonsoroko** [comment]
from the log file you need to try to run `/data/data/org.xbmc.kodi/files/plugin.video.elementum/bin/android_arm/elementum` from any terminal emulator, like termux.

interesting that if binary failed to run then python part should have caught the exception and print it. at least it works on my linux system with cases like no permissions or different arch.

**Comment by elgatito** [comment]
@antonsoroko yes, strange that we do not log execution attempt error in the log file, so we try to execute and then nothing, we are trying again and again.

**Comment by antonsoroko** [comment]
on my system it writes exception to log file:
<details><summary>example</summary>

```
2021-06-30 01:11:09.053 T:16494   ERROR <general>: Exception in thread 
2021-06-30 01:11:09.053 T:16494   ERROR <general>: Thread-2
2021-06-30 01:11:09.053 T:16494   ERROR <general>: :
                                                   
2021-06-30 01:11:09.053 T:16494   ERROR <general>: Traceback (most recent call last):
                                                   
2021-06-30 01:11:09.053 T:16494   ERROR <general>:   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
                                                   
2021-06-30 01:11:09.053 T:16494   ERROR <general>:     
2021-06-30 01:11:09.053 T:16494   ERROR <general>: self.run()
2021-06-30 01:11:09.053 T:16494   ERROR <general>: 
                                                   
2021-06-30 01:11:09.053 T:16494   ERROR <general>:   File "/usr/lib/python3.9/threading.py", line 892, in run
                                                   
2021-06-30 01:11:09.054 T:16494   ERROR <general>:     
2021-06-30 01:11:09.054 T:16494   ERROR <general>: self._target(*self._args, **self._kwargs)
2021-06-30 01:11:09.054 T:16494   ERROR <general>: 
                                                   
2021-06-30 01:11:09.054 T:16494   ERROR <general>:   File "/home/xxx/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 304, in elementumd_thread
                                                   
2021-06-30 01:11:09.054 T:16494   ERROR <general>:     
2021-06-30 01:11:09.054 T:16494   ERROR <general>: proc = start_elementumd(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
2021-06-30 01:11:09.054 T:16494   ERROR <general>: 
                                                   
2021-06-30 01:11:09.054 T:16494   ERROR <general>:   File "/home/xxx/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 261, in start_elementumd
                                                   
2021-06-30 01:11:09.054 T:16494   ERROR <general>:     
2021-06-30 01:11:09.054 T:16494   ERROR <general>: return subprocess.Popen(args, **kwargs)
2021-06-30 01:11:09.054 T:16494   ERROR <general>: 
                                                   
2021-06-30 01:11:09.054 T:16494   ERROR <general>:   File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
                                                   
2021-06-30 01:11:09.054 T:16494   ERROR <general>:     
2021-06-30 01:11:09.054 T:16494   ERROR <general>: self._execute_child(args, executable, preexec_fn, close_fds,
2021-06-30 01:11:09.054 T:16494   ERROR <general>: 
                                                   
2021-06-30 01:11:09.054 T:16494   ERROR <general>:   File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
                                                   
2021-06-30 01:11:09.054 T:16494   ERROR <general>:     
2021-06-30 01:11:09.054 T:16494   ERROR <general>: raise child_exception_type(errno_num, err_msg, err_filename)
2021-06-30 01:11:09.054 T:16494   ERROR <general>: 
                                                   
2021-06-30 01:11:09.054 T:16494   ERROR <general>: OSError
2021-06-30 01:11:09.054 T:16494   ERROR <general>: : 
2021-06-30 01:11:09.054 T:16494   ERROR <general>: [Errno 8] Exec format error: '/home/xxx/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_x64/elementum'
2021-06-30 01:11:09.054 T:16494   ERROR <general>: 
                                                   
2021-06-30 01:11:09.054 T:16494   DEBUG <general>: .
```

</details>
