### ISSUE TITLE
Version 0.1.84 update error

### ISSUE THREAD

**Issue by matke-84** [elgatito/plugin.video.elementum#859]
`2022-01-10 23:13:01.283 T:12552 WARNING <general>: Repository add-on repository.elementum uses plain HTTP for add-on downloads in path http://127.0.0.1:65220/repository/elgatito/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2022-01-10 23:13:01.824 T:12552    INFO <general>: CAddonMgr::ADDON::CAddonMgr::FindAddon: plugin.video.elementum v0.1.84 installed
2022-01-10 23:13:01.826 T:12212    INFO <general>: initializing python engine.
2022-01-10 23:13:01.853 T:7084  WARNING <general>: Repository add-on repository.elementum uses plain HTTP for add-on downloads in path http://127.0.0.1:65220/repository/elgatito/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2022-01-10 23:13:02.196 T:12212   ERROR <general>: Skipped 8 duplicate messages..
2022-01-10 23:13:02.196 T:12212   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'requests'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\plugin.video.elementum\service.py", line 4, in <module>
                                                       from elementum import service, config
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\plugin.video.elementum\resources\site-packages\elementum\service.py", line 4, in <module>
                                                       from elementum.rpc import server_thread
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\plugin.video.elementum\resources\site-packages\elementum\rpc.py", line 17, in <module>
                                                       from elementum.util import toUtf8, notify, getLocalizedString, getLocalizedLabel, getLocalizedText, system_information, translatePath
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\plugin.video.elementum\resources\site-packages\elementum\util.py", line 4, in <module>
                                                       import requests
                                                   ModuleNotFoundError: No module named 'requests'
                                                   -->End of Python script error report<--
                                                   
2022-01-10 23:13:02.341 T:12212    INFO <general>: Python interpreter stopped
`

**Comment by SubEdict** [comment]
Yep, same. PC 7/10, on Auto Update. Didn't try yet to download it from the site.
What did you do? :)

**Comment by matke-84** [comment]
@SubEdict The same error with manual installation.

**Comment by heartlogic** [comment]
The same error with auto-update in CoreELEC in Beeling GT King.

**Comment by antonsoroko** [comment]
looks like because of this change
https://github.com/elgatito/plugin.video.elementum/commit/c38b76dc41aa7d9dedf0c562f10d53401102b071#diff-cdef6452c375d34f287da5b950edb1ec73296f02bd7039917d24dc149695be82R4

we need to add dependency somehow.

**Comment by pitsi** [comment]
Same thing here. Elementum was updated once then it got stuck in an update loop, downloading the addon over and over, lagging my kodi stream and popping the notification that it was updated every 5 seconds. And it always ends up on 0.1.83, so I guess that is what triggers the loop. 

Happens on both kodi 19 (debian unstable x64) and on kodi 18 (libreelec x64 9.2.6).
Sorry, but I had to disable it on both systems. I would try a manual upgrade to 0.1.84 if it was available, but it is not (yet?).

**Comment by elgatito** [comment]
Version 0.1.84 is removed. Version 0.1.85 includes missing dependency.

**Comment by antonsoroko** [comment]
@matke-84 @SubEdict @pitsi please check if issue was solved with 0.1.85.

**Comment by SubEdict** [comment]
Thanks @antonsoroko  @elgatito everything back to normal, works great.
* 1 PC that **already installed** the 0.1.84 needed to completely remove and download fresh from the site.
* Second PC that **didn't yet installed** 0.1.84 got the auto-update successfully without any problem.

**Comment by antonsoroko** [comment]
@SubEdict thank you for testing!

**Comment by pitsi** [comment]
There was a blackout here while I was writing my comment a few minutes ago and all was lost. 
I won't write it again because I already forgot some parts that had to do with the update loop on kodi 18. Let's say that the upgrade to .85 was successful on both my systems and it now works as it should. 

The only weird thing that happened after the upgrade was that the message "Elementum daemon has started" that pops up as a notification at the start had become "Elementum (some number here) locale". But it got back to normal after a fresh launch of kodi.

**Comment by matke-84** [comment]
@antonsoroko Works. Thanks. 😉

**Comment by dlxmax** [comment]
Unfortunately, 0.1.84 is the only version currently in the official "Elementum Repository".

**Comment by antonsoroko** [comment]
@dlxmax 
try to install zip manually, link in readme - https://github.com/elgatito/plugin.video.elementum#download

also maybe this is there reason - https://github.com/elgatito/plugin.video.elementum/issues/861#issuecomment-1010544852
