### ISSUE TITLE
[BUG]Wrong error when have two languages search and one match result.

### ISSUE THREAD

**Issue by leandrocaldas** [elgatito/plugin.video.elementum#901]
## Context
I'm inserting some servers from Brazil and the scrap now is working very well, but I'm facing a problem with elementum translation. I could solve part of problem but now I don't know more what to do.

## Current Behavior
1- (solved by me) in Brazil we have a lot of accentuation in the words for example (ã, ç, é, á), and this cause failure during search.
my solution was insert the following in the filtering.py file:
`if use_language != 'original' and (self.convert_language(use_language) not in self.provider_languages or self.convert_language(use_language) == 'en' or use_language == 'pt-BR' or use_language == 'br'):
                                title = remove_accents(title)`
before this the accentuation was in title.
2-(to solve) one site (https://insanostorrent.com/) I can found some moves when I set languages to pt and other moves when I set it to br, because the translation to pt-br isn´t good, until here ok, I can set in server to get both (pt and br) in this way:
`"movie_keywords": "{title:br:pt}" or "movie_keywords": "{title:br}" and movie_keywords2": "{title:pt}`

it works fine and both search is done, but the big problem is when I found one for example when language is in pt, than when language is in br, and have no result, the server fail and return 404 code, after that an error occur and have nothing to show to download even if the first search in pt have positive result.

title result:
original title: emancipacion
pt : emancipação -> remove_accents(title) -> emancipacao -> this is perfect to scrap
br: emancipation-uma-historia-de-liberdade -> this not work because the correct translation should be emancipação not emancipation

the second example is the oposit:
original title: bullet train
pt : bullet-train-comboio-bala-> this not work because the correct translation should be trem bala not bullet train
url not work: https://insanostorrent.com/bullet-train-comboio-bala

br: trem-bala -> this is perfect to scrap
url work: https://insanostorrent.com/trem-bala

## Expected Behavior
I expected that I can search in both cases pt and br, and if one of this language not found, must to show the other founded and not fail the search.

## Possible Solution
if you try to get a invalid url to this site, the page not respond with 404 error, only show an image with this error printed, should to check a way to avoid this invalid error and provide the final result correct with no results or with results provided by other language.
The main idea should be pt or br not pt and br.

## Steps to Reproduce (for bugs)

my provider.json

`{
    "insanostorrent": {
        "enabled": true,
        "base_url": "https://insanostorrent.com/QUERY",
        "color": "FFF14E13",
        "general_extra": "",
        "general_keywords": "{title:pt}",
        "general_keywords2": "{title:br}",
        "general_query": "EXTRA",
        "language": "pt,br",
        "movie_extra": "",
        "movie_keywords": "{title:pt}",
        "movie_keywords2": "{title:br}",
        "movie_query": "EXTRA",
        "name": "insanostorrent",
        "parser": {
            "infohash": "",
            "key": "find_once('div', select=('class', 'meta_datos')).find_all(tag='h1')[0].text().replace('WEB-DL','').replace('HD','').replace('720p','').replace('1080p','').replace('2160p','').replace('/','').replace(' e ','').replace('Legendado','').replace('Dublado','').replace('Dual Áudio 5.1','')",
            "name": "key +'-> '+item(tag='a', order=1)",
            "peers": "20",
            "row": "find_once('div', select=('class', 'row-single'), order=1)",
            "seeds": "3",
            "size": "",
            "torrent": "item(tag='input', attribute='value', order=1)"
        },
        "separator": "-",
        "show_query": "",
        "subpage": true
    }
}`
both two logs are in same execution:
log ok was the first:

`2023-02-09 12:15:41.819 T:19884 WARNING <general>: [script.elementum.burst] [insanostorrent] >       insanostorrent search URL: https://insanostorrent.com/emancipacao
2023-02-09 12:15:41.820 T:19884   DEBUG <general>: [script.elementum.burst] Opening URL: 'https://insanostorrent.com/emancipacao'
2023-02-09 12:15:42.067 T:7808    DEBUG <general>: [script.elementum.burst] Timer: 0s / 27s
2023-02-09 12:15:42.741 T:19884   DEBUG <general>: Skipped 2 duplicate messages..
2023-02-09 12:15:42.740 T:19884   DEBUG <general>: [script.elementum.burst] Status for 'https://insanostorrent.com/emancipacao' : 200`
trash, dom result and parse ok 4 torrents founded...

`2023-02-09 12:15:42.826 T:7808    DEBUG <general>: [script.elementum.burst] Timer: 1s / 27s
2023-02-09 12:15:42.828 T:19884   DEBUG <general>: [script.elementum.burst] [insanostorrent] >>>>>> insanostorrent would send 4 torrents to Elementum <<<<<<<
2023-02-09 12:15:42.829 T:19884   DEBUG <general>: [script.elementum.burst] [insanostorrent] >>>>>> insanostorrent would send 4 torrents to Elementum after cleanup <<<<<<<`

log error:
`2023-02-09 12:15:42.829 T:19884   DEBUG <general>: [script.elementum.burst] [insanostorrent] Before keywords - Query: '{title:br}' - Extra: ''
2023-02-09 12:15:42.830 T:19884 WARNING <general>: [script.elementum.burst] [insanostorrent] Using translated 'br' title 'emancipation uma historia de liberdade'
2023-02-09 12:15:42.830 T:19884   DEBUG <general>: [script.elementum.burst] [insanostorrent] After keywords  - Query: 'emancipation%20uma%20historia%20de%20liberdade' - Extra: ''
2023-02-09 12:15:42.830 T:19884   DEBUG <general>: [script.elementum.burst] -   insanostorrent query: 'emancipation%20uma%20historia%20de%20liberdade'
2023-02-09 12:15:42.830 T:19884   DEBUG <general>: [script.elementum.burst] --  insanostorrent url_search before token: 'https://insanostorrent.com/emancipation-uma-historia-de-liberdade'
2023-02-09 12:15:42.830 T:19884   DEBUG <general>: [script.elementum.burst] --- insanostorrent using POST payload: {}
2023-02-09 12:15:42.830 T:19884   DEBUG <general>: [script.elementum.burst] ----insanostorrent filtering with post_data: {}
2023-02-09 12:15:42.831 T:19884 WARNING <general>: [script.elementum.burst] [insanostorrent] >       insanostorrent search URL: https://insanostorrent.com/emancipation-uma-historia-de-liberdade
2023-02-09 12:15:42.831 T:19884   DEBUG <general>: [script.elementum.burst] Opening URL: 'https://insanostorrent.com/emancipation-uma-historia-de-liberdade'
2023-02-09 12:15:43.077 T:7808    DEBUG <general>: [script.elementum.burst] Timer: 1s / 27s
2023-02-09 12:15:43.259 T:8028    DEBUG <general>: AddOnLog: pvr.hts: new connection requested
2023-02-09 12:15:43.329 T:7808    DEBUG <general>: [script.elementum.burst] Timer: 1s / 27s
2023-02-09 12:15:43.409 T:19884   DEBUG <general>: [script.elementum.burst] Status for 'https://insanostorrent.com/emancipation-uma-historia-de-liberdade' : 404
2023-02-09 12:15:43.409 T:19884   DEBUG <general>: [script.elementum.burst] [insanostorrent] Accepted resolutions: ['filter_240p', 'filter_480p', 'filter_720p', 'filter_1080p', 'filter_2k', 'filter_4k']`

I removed some trash and DOM result:

`2023-02-09 12:15:43.444 T:19884   ERROR <general>: Exception in thread 
2023-02-09 12:15:43.444 T:19884   ERROR <general>: Thread-1
2023-02-09 12:15:43.444 T:19884   ERROR <general>: :                        
2023-02-09 12:15:43.444 T:19884   ERROR <general>: Traceback (most recent call last):                        
2023-02-09 12:15:43.444 T:19884   ERROR <general>:   File "C:\Program Files\Kodi\system\python\Lib\threading.py", line 932, in _bootstrap_inner                               
2023-02-09 12:15:43.445 T:19884   ERROR <general>:     
2023-02-09 12:15:43.445 T:19884   ERROR <general>: self.run()
2023-02-09 12:15:43.445 T:19884   ERROR <general>:                                           
2023-02-09 12:15:43.445 T:19884   ERROR <general>:   File "C:\Program Files\Kodi\system\python\Lib\threading.py", line 870, in run                                           
2023-02-09 12:15:43.446 T:19884   ERROR <general>:     
2023-02-09 12:15:43.446 T:19884   ERROR <general>: self._target(*self._args, **self._kwargs)
2023-02-09 12:15:43.446 T:19884   ERROR <general>:                                             
2023-02-09 12:15:43.446 T:19884   ERROR <general>:   File "C:\Users\leand\AppData\Roaming\Kodi\addons\script.elementum.burst\burst\burst.py", line 645, in run_provider                                           
2023-02-09 12:15:43.447 T:19884   ERROR <general>:     
2023-02-09 12:15:43.447 T:19884   ERROR <general>: results = process(provider=provider, generator=extract_torrents, filtering=filterInstance, has_special=payload['has_special'], skip_auth=payload['skip_auth'], start_time=start_time, timeout=timeout)
2023-02-09 12:15:43.447 T:19884   ERROR <general>:                                      
2023-02-09 12:15:43.447 T:19884   ERROR <general>:   File "C:\Users\leand\AppData\Roaming\Kodi\addons\script.elementum.burst\burst\provider.py", line 323, in process
2023-02-09 12:15:43.447 T:19884   ERROR <general>:     
2023-02-09 12:15:43.447 T:19884   ERROR <general>: generate_payload(provider,
2023-02-09 12:15:43.447 T:19884   ERROR <general>: 
2023-02-09 12:15:43.447 T:19884   ERROR <general>:   File "C:\Users\leand\AppData\Roaming\Kodi\addons\script.elementum.burst\burst\provider.py", line 45, in generate_payload
2023-02-09 12:15:43.448 T:19884   ERROR <general>:     
2023-02-09 12:15:43.449 T:19884   ERROR <general>: for id, name, info_hash, uri, size, seeds, peers in generator:
2023-02-09 12:15:43.449 T:19884   ERROR <general>:                                                  
2023-02-09 12:15:43.449 T:19884   ERROR <general>:   File "C:\Users\leand\AppData\Roaming\Kodi\addons\script.elementum.burst\burst\burst.py", line 336, in extract_torrents                                            
2023-02-09 12:15:43.450 T:19884   ERROR <general>:     
2023-02-09 12:15:43.450 T:19884   ERROR <general>: key = eval(key_search) if key_search else ""
2023-02-09 12:15:43.450 T:19884   ERROR <general>:                                                 
2023-02-09 12:15:43.450 T:19884   ERROR <general>:   File "<string>", line 1, in <module>                                                 
2023-02-09 12:15:43.452 T:19884   ERROR <general>: IndexError
2023-02-09 12:15:43.452 T:19884   ERROR <general>: : 
2023-02-09 12:15:43.452 T:19884   ERROR <general>: list index out of range
2023-02-09 12:15:43.452 T:19884   ERROR <general>:                                              
2023-02-09 12:15:43.452 T:19884   DEBUG <general>: .
2023-02-09 12:15:43.579 T:7808    DEBUG <general>: Skipped 1 duplicate messages..
2023-02-09 12:15:43.579 T:7808    DEBUG <general>: [script.elementum.burst] Timer: 1s / 27s
2023-02-09 12:15:43.831 T:7808    DEBUG <general>: [script.elementum.burst] Timer: 2s / 27s
2023-02-09 12:15:44.642 T:10988   DEBUG <general>: Skipped 3 duplicate messages..
2023-02-09 12:15:44.642 T:10988   DEBUG <general>: ------ Window Deinit (Pointer.xml) ------
2023-02-09 12:15:44.837 T:7808    DEBUG <general>: [script.elementum.burst] Timer: 3s / 27s
2023-02-09 12:15:45.841 T:7808    DEBUG <general>: Skipped 3 duplicate messages..
2023-02-09 12:15:45.841 T:7808    DEBUG <general>: [script.elementum.burst] Timer: 4s / 27s`

repeted it for a long time then:

`2023-02-09 12:15:53.260 T:8028    ERROR <general>: AddOnLog: pvr.hts: unable to connect to 192.168.1.6:9982
2023-02-09 12:16:03.259 T:8028    DEBUG <general>: AddOnLog: pvr.hts: new connection requested
2023-02-09 12:16:08.956 T:7808    ERROR <general>: Skipped 3 duplicate messages..
2023-02-09 12:16:08.956 T:7808    ERROR <general>: [script.elementum.burst] insanostorrent Provedor Lento
2023-02-09 12:16:08.957 T:7808    DEBUG <general>: [script.elementum.burst] all provider_results of 0: []
2023-02-09 12:16:08.957 T:7808    DEBUG <general>: [script.elementum.burst] all filtered_results of 0: []
2023-02-09 12:16:08.957 T:7808  WARNING <general>: [script.elementum.burst] Providers returned 0 results in 27.17 seconds`

link ok - https://insanostorrent.com/emancipacao
link not ok - https://insanostorrent.com/emantipation

## Your Environment

* Version used:
elementum 0.1.83
* Environment name and version:
LibreElec 11 
* Operating System and version:
kernel v6.1.8 LTS
* Link to Kodi debug log:
[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/10698817/kodi.log)

**Comment by antonsoroko** [comment]
@leandrocaldas hi.
1. looks like you misread the purpose of `"language": "pt,br"` field in `providers.json` and thus you had to change the code.
if you look here
https://github.com/elgatito/script.elementum.burst/blob/master/burst/filtering.py#L475-L477
you will see that if tracker does not actually support full features of language (like accents) - then we remove accents.
your tracker seems to use queries without accents, thus you should set `"language": null,` instead of `"language": "pt,br"`.

2. I guess the fastest approach is for you to take a look into the code to see where you can add python exception handling and then make a PR (sorry :-) ). Looks like this is super rare case when tracker returns 404 and thus this is not handled yet.
