### ISSUE TITLE
[Request] Option to download the entire season pack if chosen

### ISSUE THREAD

**Issue by herrwusel** [elgatito/plugin.video.elementum#93]
Copy from https://github.com/scakemyer/plugin.video.quasar/issues/840

**Comment by Yutsa** [comment]
What would be really cool for me is an option to download a whole season but put the files in the same place where the `strm` files are stored. What would be even cooler is to donwload the season (or single episode) in the show directory delete the `strm` file corresponding to the episodes downloaded.

Could something like that be possible @elgatito ? I could try and develop it if you agree and can provide some guidance.

**Comment by elgatito** [comment]
@herrwusel @Yutsa @antonsoroko
There is a new option in 0.1.70 to select if you want to download only the playing file (at it was before), or you want to download also current season episodes, or you want to download all files.

**Comment by antonsoroko** [comment]
@elgatito 

https://paste.kodi.tv/juxihodopa.kodi

with "download season files" it asks to choose episode (i choose 1st) then it starts download all season files (i can see them on FS) like intended, then it also starts video playback but then elementum crashes and restart:
```
2021-03-12 14:24:52.535 T:477467 WARNING <general>: [plugin.video.elementum] panic: runtime error: index out of range [-1]
2021-03-12 14:24:52.535 T:477467 WARNING <general>: [plugin.video.elementum] 
2021-03-12 14:24:52.535 T:477467 WARNING <general>: [plugin.video.elementum] goroutine 6892 [running]:
2021-03-12 14:24:52.535 T:477467 WARNING <general>: [plugin.video.elementum] github.com/elgatito/elementum/bittorrent.getShowSeasonEpisode(0xbefb, 0x7, 0x0, 0xc000056000, 0xc0000c54d0, 0x56adfc, 0xc0004c1980, 0x300000002)
2021-03-12 14:24:52.554 T:477467 WARNING <general>: [plugin.video.elementum]    /var/lib/jenkins/workspace/elementum/bittorrent/player.go:1429 +0x1c7

```

**Comment by antonsoroko** [comment]
```
2021-03-12 14:50:02.911 T:477467 WARNING <general>: [plugin.video.elementum] panic: runtime error: index out of range [-1]
2021-03-12 14:50:02.912 T:477467 WARNING <general>: [plugin.video.elementum] 
2021-03-12 14:50:02.913 T:477467 WARNING <general>: [plugin.video.elementum] goroutine 16388 [running]:
2021-03-12 14:50:02.913 T:477467 WARNING <general>: [plugin.video.elementum] github.com/elgatito/elementum/bittorrent.getShowSeasonEpisode(0x12293, 0x1, 0x0, 0xc0007f94d0, 0x100000000642996, 0xc0007f94e0, 0x56b46a, 0xc000056000)
2021-03-12 14:50:02.913 T:477467 WARNING <general>: [plugin.video.elementum] 	/var/lib/jenkins/workspace/elementum/bittorrent/player.go:1429 +0x1c7
2021-03-12 14:50:02.913 T:477467 WARNING <general>: [plugin.video.elementum] github.com/elgatito/elementum/bittorrent.(*Player).processUpNextShow(0xc0003d3e00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2021-03-12 14:50:02.964 T:477467 WARNING <general>: [plugin.video.elementum] 	/var/lib/jenkins/workspace/elementum/bittorrent/player.go:1281 +0xa7
```

and also this

**Comment by elgatito** [comment]
@antonsoroko There is an update 0.1.71 with the fix.

**Comment by antonsoroko** [comment]
i tested all 3 options - works ok. thank you!
