### ISSUE TITLE
Kodi crashes on startup due to platform_detect

### ISSUE THREAD

**Issue by doraskayo** [elgatito/plugin.video.elementum#930]
## Expected Behavior
Kodi doesn't crash.

## Current Behavior
Kodi crashes on startup.

The backtrace from the crashing thread is below. Sorry for the lack of symbols, but apparently obtaining them in LibreELEC is not trivial. It seems to be related to the call to `dlclose`.
```
Thread 1 (Thread 0x7f52daffd6c0 (LWP 1500)):
#0  0x00007f534e654ec9 in ?? () from /lib64/ld-linux-x86-64.so.2
#1  0x00007f534b492bb3 in _dl_catch_exception () from /usr/lib/libc.so.6
#2  0x00007f534b492c4f in _dl_catch_error () from /usr/lib/libc.so.6
#3  0x00007f534b3d84e7 in ?? () from /usr/lib/libc.so.6
#4  0x00007f534b3d8296 in dlclose () from /usr/lib/libc.so.6
#5  0x00007f5324b20052 in ?? () from /usr/lib/python3.11/lib-dynload/_ctypes.so
#6  0x00007f5324b1db7a in ?? () from /usr/lib/python3.11/lib-dynload/_ctypes.so
#7  0x00007f5324b1e1dd in ffi_call () from /usr/lib/python3.11/lib-dynload/_ctypes.so
#8  0x00007f5324b15d3c in ?? () from /usr/lib/python3.11/lib-dynload/_ctypes.so
#9  0x00007f5324b0f686 in ?? () from /usr/lib/python3.11/lib-dynload/_ctypes.so
#10 0x00007f534dd04ebb in _PyObject_MakeTpCall () from /usr/lib/libpython3.11.so.1.0
#11 0x00007f534dcb4ce4 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.11.so.1.0
#12 0x00007f534ddd35f0 in ?? () from /usr/lib/libpython3.11.so.1.0
#13 0x00007f534ddd3693 in PyEval_EvalCode () from /usr/lib/libpython3.11.so.1.0
#14 0x00007f534ddcbde0 in ?? () from /usr/lib/libpython3.11.so.1.0
#15 0x00007f534dd451f2 in ?? () from /usr/lib/libpython3.11.so.1.0
#16 0x00007f534dcb1462 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.11.so.1.0
#17 0x00007f534ddd35f0 in ?? () from /usr/lib/libpython3.11.so.1.0
#18 0x00007f534dd0569d in ?? () from /usr/lib/libpython3.11.so.1.0
#19 0x00007f534dd05877 in PyObject_CallMethodObjArgs () from /usr/lib/libpython3.11.so.1.0
#20 0x00007f534ddfa0b9 in PyImport_ImportModuleLevelObject () from /usr/lib/libpython3.11.so.1.0
#21 0x00007f534dcb5e38 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.11.so.1.0
#22 0x00007f534ddd35f0 in ?? () from /usr/lib/libpython3.11.so.1.0
#23 0x00007f534ddd3693 in PyEval_EvalCode () from /usr/lib/libpython3.11.so.1.0
#24 0x00007f534ddcbde0 in ?? () from /usr/lib/libpython3.11.so.1.0
#25 0x00007f534dd451f2 in ?? () from /usr/lib/libpython3.11.so.1.0
#26 0x00007f534dcb1462 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.11.so.1.0
#27 0x00007f534ddd35f0 in ?? () from /usr/lib/libpython3.11.so.1.0
#28 0x00007f534dd0569d in ?? () from /usr/lib/libpython3.11.so.1.0
#29 0x00007f534dd05877 in PyObject_CallMethodObjArgs () from /usr/lib/libpython3.11.so.1.0
#30 0x00007f534ddfa0b9 in PyImport_ImportModuleLevelObject () from /usr/lib/libpython3.11.so.1.0
#31 0x00007f534dcb5e38 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.11.so.1.0
#32 0x00007f534ddd35f0 in ?? () from /usr/lib/libpython3.11.so.1.0
#33 0x00007f534ddd3693 in PyEval_EvalCode () from /usr/lib/libpython3.11.so.1.0
#34 0x00007f534ddcbde0 in ?? () from /usr/lib/libpython3.11.so.1.0
#35 0x00007f534dd451f2 in ?? () from /usr/lib/libpython3.11.so.1.0
#36 0x00007f534dcb1462 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.11.so.1.0
#37 0x00007f534ddd35f0 in ?? () from /usr/lib/libpython3.11.so.1.0
#38 0x00007f534dd0569d in ?? () from /usr/lib/libpython3.11.so.1.0
#39 0x00007f534dd05877 in PyObject_CallMethodObjArgs () from /usr/lib/libpython3.11.so.1.0
#40 0x00007f534ddfa0b9 in PyImport_ImportModuleLevelObject () from /usr/lib/libpython3.11.so.1.0
#41 0x00007f534ddca90e in ?? () from /usr/lib/libpython3.11.so.1.0
#42 0x00007f534dd451f2 in ?? () from /usr/lib/libpython3.11.so.1.0
#43 0x00007f534dcb1462 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.11.so.1.0
#44 0x00007f534ddd35f0 in ?? () from /usr/lib/libpython3.11.so.1.0
#45 0x00007f534dd0569d in ?? () from /usr/lib/libpython3.11.so.1.0
#46 0x00007f534dd05877 in PyObject_CallMethodObjArgs () from /usr/lib/libpython3.11.so.1.0
#47 0x00007f534ddf9c5c in PyImport_ImportModuleLevelObject () from /usr/lib/libpython3.11.so.1.0
#48 0x00007f534dcb5e38 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.11.so.1.0
#49 0x00007f534ddd35f0 in ?? () from /usr/lib/libpython3.11.so.1.0
#50 0x00007f534ddd3693 in PyEval_EvalCode () from /usr/lib/libpython3.11.so.1.0
#51 0x00007f534de11d83 in ?? () from /usr/lib/libpython3.11.so.1.0
#52 0x00007f534de11f86 in ?? () from /usr/lib/libpython3.11.so.1.0
#53 0x00007f534de12060 in ?? () from /usr/lib/libpython3.11.so.1.0
#54 0x00007f534de1517c in PyRun_FileExFlags () from /usr/lib/libpython3.11.so.1.0
#55 0x0000000000abeb50 in CPythonInvoker::executeScript(_IO_FILE*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, _object*) ()
#56 0x0000000000ad02d0 in CPythonInvoker::execute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, std::allocator<std::__cxx11::basic_string<wc
har_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > >&) ()
#57 0x0000000000ad0eaa in CPythonInvoker::execute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::
char_traits<char>, std::allocator<char> > > > const&) ()
#58 0x0000000001531c4e in CLanguageInvokerThread::Process() ()
#59 0x0000000000e5c1c3 in CThread::Action() ()
#60 0x00000000016b88c3 in ?? ()
#61 0x0000000000e5c42f in ?? ()
#62 0x00007f534b214403 in ?? () from /usr/lib/libstdc++.so.6
#63 0x00007f534b3dc460 in ?? () from /usr/lib/libc.so.6
#64 0x00007f534b455a2c in ?? () from /usr/lib/libc.so.6
```

## Workaround
I confirmed that this change avoids the crash:
``` patch
--- platform.py.orig	2023-07-07 00:12:35.521866373 +0300
+++ platform.py	2023-07-07 00:12:50.288039412 +0300
@@ -30,38 +30,7 @@
 # Proper library should return '42' as a result to a 'int test()' method call.
 # We give preference to a 'higher' arch (x64 over x96, arm64 over armv7, etc).
 def detect_platform():
-    for system in platforms.keys():
-        for arch in platforms.get(system):
-            try:
-                library_path = get_library_path(system, arch)
-                if not library_path:
-                    continue
-
-                # Try to load a library
-                lib = cdll.LoadLibrary(library_path)
-
-                # Make library call
-                lib.test.restype = c_int
-                result = lib.test()
-
-                # Close the library, to avoid locking the file by a process
-                if '.so' in library_path:
-                    try:
-                        lib.dlclose(lib._handle)
-                    except:
-                        pass
-                else:
-                    try:
-                        from ctypes import windll
-                        windll.kernel32.FreeLibrary(lib._handle)
-                    except:
-                        pass
-
-                if result and result == 42:
-                    return system + "-" + arch
-            except:
-                pass
-    return None
+    return "linux-x64"
 
 def get_library_path(system, arch):
     sub_dir = system + "_" + arch
```
## Steps to Reproduce (for bugs)

1. Install plugin.video.elementum version 0.1.91
2. Crash

## Context
The backtrace suggests that the call to `dlclose` results in a crash.

This change **does not** avoid the crash, which suggests that the cause for the crash is not related to the attempt to load foreign libraries.
``` patch
--- platform.py.orig	2023-07-07 00:14:37.188346998 +0300
+++ platform.py	2023-07-07 00:11:58.483203528 +0300
@@ -3,25 +3,8 @@
 from ctypes import c_int, cdll
 
 platforms = {
-    'android': [
-        'arm64',
-        'arm',
-        'x64',
-        'x86'
-    ],
     'linux': [
-        'arm64',
-        'armv7',
-        'armv6',
-        'x64',
-        'x86'
-    ],
-    'windows': [
         'x64',
-        'x86'
-    ],
-    'darwin': [
-        'x64'
     ]
 }
 
```

## Your Environment
* Version used:
   `0.1.91`
* Environment name and version:
   `Kodi (20.1 (20.1.0) Git:20.1-Nexus)`
* Operating System and version:
   ```
   Arch: x86_64
   Kernel: Linux 6.1.19 #1 SMP Sat Mar 18 16:52:01 UTC 2023
   Release: LibreELEC 11.0.1
   ```
   ```
   # /usr/lib64/ld-linux-x86-64.so.2 --version
   ld.so (GNU libc) stable release version 2.36.
   Copyright (C) 2022 Free Software Foundation, Inc.
   This is free software; see the source for copying conditions.
   There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
   PARTICULAR PURPOSE.
   ```

**Comment by elgatito** [comment]
@doraskayo Interesting why it cannot close the library.

Can you try to revert everything and comment out only this part:
```
-                if '.so' in library_path:
-                    try:
-                        lib.dlclose(lib._handle)
-                    except:
-                        pass
-                else:
-                    try:
-                        from ctypes import windll
-                        windll.kernel32.FreeLibrary(lib._handle)
-                    except:
-                        pass
```

**Comment by giddyup69** [comment]
> @doraskayo Interesting why it cannot close the library.
> 
> Can you try to revert everything and comment out only this part:
> 
> ```
> -                if '.so' in library_path:
> -                    try:
> -                        lib.dlclose(lib._handle)
> -                    except:
> -                        pass
> -                else:
> -                    try:
> -                        from ctypes import windll
> -                        windll.kernel32.FreeLibrary(lib._handle)
> -                    except:
> -                        pass
> ```

@elgatito I tried this myself and it corrects the problem.  

I assume I had the same problem as doraskayo.  Libreelec would crash as soon as Kodi started.  The issue started approximately 2 days ago for me.  Commenting out as above corrects the problem.  Everything working now.

**Comment by giddyup69** [comment]
here is my log file from safemode https://pastebin.com/iRmhw42F after installing elementum and it crashes the os

not sure if helpful or not

**Comment by elgatito** [comment]
Try to install 0.1.92.

**Comment by giddyup69** [comment]
> Try to install 0.1.92.

@elgatito 0.1.92 tested and working fine

**Comment by doraskayo** [comment]
@elgatito, 0.1.92 works! I'm closing this issue as resolved.
