### ISSUE TITLE
Linux x86-64 + "Force start as a library" = crash if there was error in elementum settings during the start

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#962]
## Current Behavior

с включенным local_force_library - если сделать папку загрузок незаписываемой (или как-то по другому вызвать ошибку при старте), то неважно починишь ошибку (поменяешь путь или права на старый путь него) или нет (просто нажмёшь отмена) - коди сегфолтится. для бинаря просто рестарт и всё ок.

## Steps to Reproduce (for bugs)

1. remove write permission from download directory
2. start kodi
3. see errors in UI, click ok
4. fix or ignore error and then click ok to close elementum settings
5. "Segmentation fault"

## Your Environment

* Version used: 0.1.99

* Environment name and version: kodi 20.2

* Operating System and version: linux 6.5.0-14-generic x86-64

* Link to Kodi debug log:

```
INFO  main         ▶ main             Starting Elementum daemon in shared library mode
Redirecting Stdout/Stderr to /home/user/.kodi/temp/elementum/elementum.log
INFO  main         ▶ main             Version: 0.1.99 LibTorrent: 1.1.14.0 Go: go1.21.1, Threads: 8
DEBU  xbmc         ▶ Init             Could not connect to the host ::1: dial tcp [::1]:9090: connect: connection refused
DEBU  xbmc         ▶ Init             Adding local host 127.0.0.1
INFO  config       ▶ Reload           Reloading configuration...
NOTI  config       ▶ Reload           Paths translated by Kodi: Download: /home/user/.kodi/temp/elementum_downloads , Library: /home/user/.kodi/elementum_library , Torrents: /home/user/.kodi/temp/elementum_torrents , Profile: /home/user/.kodi/userdata/addon_data/plugin.video.elementum/ , Default Storage: File
WARN  config       ▶ func1            Addon settings not properly set, opening settings window: &errors.errorString{s:"Cannot writeto download location '/home/user/.kodi/temp/elementum_downloads': &fs.PathError{Op:\"open\", Path:\"/home/user/.kodi/temp/elementum_downloads/.writable\", Err:0xd}"}
ERRO  exit         ▶ PanicWithCode    Panic: Could not reload configuration
ERRO  exit         ▶ PanicWithCode    Stacktrace:
goroutine 17 [running, locked to thread]:
runtime/debug.Stack()
/usr/x86_64-linux-gnu/go/src/runtime/debug/stack.go:24 +0x5e
github.com/elgatito/elementum/exit.PanicWithCode({0x7fabe2082518?, 0xc000119590}, 0x0?)
/go/src/github.com/elgatito/elementum/exit/exit.go:72 +0xe5
github.com/elgatito/elementum/config.Reload.func1()
/go/src/github.com/elgatito/elementum/config/config.go:368 +0x425
panic({0x7fabe1f799a0?, 0xc0004c1ff0?})
/usr/x86_64-linux-gnu/go/src/runtime/panic.go:914 +0x21f
github.com/elgatito/elementum/exit.PanicCovered(...)
/go/src/github.com/elgatito/elementum/exit/exit.go:61
github.com/elgatito/elementum/config.Reload()
/go/src/github.com/elgatito/elementum/config/config.go:480 +0x5af9
main.main()
/go/src/github.com/elgatito/elementum/main.go:149 +0x3d7
main.startWithLogAndArgs(0x0?, 0x7fabe0bc8c01?)
/go/src/github.com/elgatito/elementum/build_shared.go:81 +0xaa
ERRO  main         ▶ main             Could not get addon configuration: Could not reload configuration
Segmentation fault (core dumped)
```

**Comment by antonsoroko** [comment]
@elgatito теперь не падает, но и не перезапускается при ошибке (не зависимо от того , исправил ли я права на папку загрузок или нет, до того как нажать ок в настройках).
в консоли:
```
libva info: VA-API version 1.19.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_18
libva info: va_openDriver() returns 0
Redirecting Stdout/Stderr to /home/user/.kodi/temp/elementum/elementum.log
INFO  main         ▶ main             Starting Elementum daemon in shared library mode
INFO  main         ▶ main             Version: 0.1.99-5-ge3da4da LibTorrent: 1.1.14.0 Go: go1.21.5, Threads: 8
DEBU  xbmc         ▶ Init             Could not connect to the host ::1: dial tcp [::1]:9090: connect: connection refused
DEBU  xbmc         ▶ Init             Adding local host 127.0.0.1
INFO  config       ▶ Reload           Reloading configuration...
NOTI  config       ▶ Reload           Paths translated by Kodi: Download: /home/user/.kodi/temp/elementum_downloads , Library: /home/user/.kodi/elementum_library , Torrents: /home/user/.kodi/temp/elementum_torrents , Profile: /home/user/.kodi/userdata/addon_data/plugin.video.elementum/ , Default Storage: File
WARN  config       ▶ func2            Addon settings not properly set, opening settings window: &errors.errorString{s:"Cannot writeto download location '/home/user/.kodi/temp/elementum_downloads': &fs.PathError{Op:\"open\", Path:\"/home/user/.kodi/temp/elementum_downloads/.writable\", Err:0xd}"}
ERRO  exit         ▶ PanicWithCode    Panic: Could not reload configuration
ERRO  exit         ▶ PanicWithCode    Stacktrace:
goroutine 17 [running, locked to thread]:
runtime/debug.Stack()
/snap/go/10455/src/runtime/debug/stack.go:24 +0x5e
github.com/elgatito/elementum/exit.PanicWithCode({0x7f348388cca8?, 0xc0004ec510}, 0x0?)
/home/user/work/elementum/exit/exit.go:73 +0xe5
github.com/elgatito/elementum/config.Reload.func2()
/home/user/work/elementum/config/config.go:383 +0x425
panic({0x7f34837891e0?, 0xc000616530?})
/snap/go/10455/src/runtime/panic.go:920 +0x270
github.com/elgatito/elementum/exit.PanicCovered(...)
/home/user/work/elementum/exit/exit.go:62
github.com/elgatito/elementum/config.Reload()
/home/user/work/elementum/config/config.go:495 +0x5bf9
main.main()
/home/user/work/elementum/main.go:163 +0x3d7
main.startWithLogAndArgs(0x0?, 0x7f34825e2201?)
/home/user/work/elementum/build_shared.go:87 +0xe5
```

лог коди https://paste.ubuntu.com/p/KWVRFrNHQP/

и ещё пару проблем:
теперь в логе kodi нет логов от go.
а `.kodi/temp/elementum/elementum.log` не создался.

**Comment by elgatito** [comment]
@antonsoroko У меня нормально перезапускалось, но на windows. Логика перезапуска не менялась и в логе я вижу возврат из библиотеки.

Попробуй закомментировать эти строки и перезапустить Коди:

`daemon.py`
```
# Instruct monitor to close and stop waiting for this thread to join
    monitor.close()
```

**Comment by antonsoroko** [comment]
тоже самое:
консоль
```
Redirecting Stdout/Stderr to /home/user/.kodi/temp/elementum/elementum.log
INFO  main         ▶ main             Starting Elementum daemon in shared library mode
INFO  main         ▶ main             Version: 0.1.99-5-ge3da4da LibTorrent: 1.1.14.0 Go: go1.21.5, Threads: 8
DEBU  xbmc         ▶ Init             Could not connect to the host ::1: dial tcp [::1]:9090: connect: connection refused
DEBU  xbmc         ▶ Init             Adding local host 127.0.0.1
INFO  config       ▶ Reload           Reloading configuration...
NOTI  config       ▶ Reload           Paths translated by Kodi: Download: /home/user/.kodi/temp/elementum_downloads , Library: /home/user/.kodi/elementum_library , Torrents: /home/user/.kodi/temp/elementum_torrents , Profile: /home/user/.kodi/userdata/addon_data/plugin.video.elementum/ , Default Storage: File
WARN  config       ▶ func2            Addon settings not properly set, opening settings window: &errors.errorString{s:"Cannot writeto download location '/home/user/.kodi/temp/elementum_downloads': &fs.PathError{Op:\"open\", Path:\"/home/user/.kodi/temp/elementum_downloads/.writable\", Err:0xd}"}
ERRO  exit         ▶ PanicWithCode    Panic: Could not reload configuration
ERRO  exit         ▶ PanicWithCode    Stacktrace:
goroutine 17 [running, locked to thread]:
runtime/debug.Stack()
/snap/go/10455/src/runtime/debug/stack.go:24 +0x5e
github.com/elgatito/elementum/exit.PanicWithCode({0x7efb1f88cca8?, 0xc0004ac5a0}, 0x0?)
/home/user/work/elementum/exit/exit.go:73 +0xe5
github.com/elgatito/elementum/config.Reload.func2()
/home/user/work/elementum/config/config.go:383 +0x425
panic({0x7efb1f7891e0?, 0xc000680600?})
/snap/go/10455/src/runtime/panic.go:920 +0x270
github.com/elgatito/elementum/exit.PanicCovered(...)
/home/user/work/elementum/exit/exit.go:62
github.com/elgatito/elementum/config.Reload()
/home/user/work/elementum/config/config.go:495 +0x5bf9
main.main()
/home/user/work/elementum/main.go:163 +0x3d7
main.startWithLogAndArgs(0x0?, 0x7efb1e5e2201?)
/home/user/work/elementum/build_shared.go:87 +0xe5
```
лог https://paste.ubuntu.com/p/Xj9Ftny6Kb/

**Comment by antonsoroko** [comment]
@elgatito 

а вот сейчас взял https://github.com/elgatito/plugin.video.elementum/commit/57c36d2d9e0488d2398dd4c64814d656c978192f и без коментирования `monitor.close()` - работает!

но `elementum.log` файл не создаёт всё равно. но зато теперь после старта пишет в лог коди как и бинарь версия.

```
Redirecting Stdout/Stderr to /home/user/.kodi/temp/elementum/elementum.log
INFO  main         ▶ main             Starting Elementum daemon in shared library mode
INFO  main         ▶ main             Version: 0.1.99-5-ge3da4da LibTorrent: 1.1.14.0 Go: go1.21.5, Threads: 8
DEBU  xbmc         ▶ Init             Could not connect to the host ::1: dial tcp [::1]:9090: connect: connection refused
DEBU  xbmc         ▶ Init             Adding local host 127.0.0.1
INFO  config       ▶ Reload           Reloading configuration...
NOTI  config       ▶ Reload           Paths translated by Kodi: Download: /home/user/.kodi/temp/elementum_downloads , Library: /home/user/.kodi/elementum_library , Torrents: /home/user/.kodi/temp/elementum_torrents , Profile: /home/user/.kodi/userdata/addon_data/plugin.video.elementum/ , Default Storage: File
WARN  config       ▶ func2            Addon settings not properly set, opening settings window: &errors.errorString{s:"Cannot writeto download location '/home/user/.kodi/temp/elementum_downloads': &fs.PathError{Op:\"open\", Path:\"/home/user/.kodi/temp/elementum_downloads/.writable\", Err:0xd}"}
ERRO  exit         ▶ PanicWithCode    Panic: Could not reload configuration
ERRO  exit         ▶ PanicWithCode    Stacktrace:
goroutine 17 [running, locked to thread]:
runtime/debug.Stack()
/snap/go/10455/src/runtime/debug/stack.go:24 +0x5e
github.com/elgatito/elementum/exit.PanicWithCode({0x7ff9af88cca8?, 0xc000442590}, 0x0?)
/home/user/work/elementum/exit/exit.go:73 +0xe5
github.com/elgatito/elementum/config.Reload.func2()
/home/user/work/elementum/config/config.go:383 +0x425
panic({0x7ff9af7891e0?, 0xc0000b6800?})
/snap/go/10455/src/runtime/panic.go:920 +0x270
github.com/elgatito/elementum/exit.PanicCovered(...)
/home/user/work/elementum/exit/exit.go:62
github.com/elgatito/elementum/config.Reload()
/home/user/work/elementum/config/config.go:495 +0x5bf9
main.main()
/home/user/work/elementum/main.go:163 +0x3d7
main.startWithLogAndArgs(0x0?, 0x7ff9ae5e2201?)
/home/user/work/elementum/build_shared.go:87 +0xe5
[GIN] 2024/01/11 - 17:19:42 | 200 |    2.725462ms |       127.0.0.1 | GET      "/?reload=20240111141854&doresume=false"
[GIN] 2024/01/11 - 17:19:44 | 200 |    2.964417ms |       127.0.0.1 | GET      "/?doresume=false"
[GIN] 2024/01/11 - 17:19:46 | 200 |     1.07119ms |       127.0.0.1 | GET      "/shows/?doresume=false"
[GIN] 2024/01/11 - 17:19:48 | 200 |  371.246867ms |       127.0.0.1 | GET      "/shows/trakt/lists/?doresume=false"
```
https://paste.ubuntu.com/p/WmfwhKWz5V/

**Comment by antonsoroko** [comment]
@elgatito 

>но elementum.log файл не создаёт всё равно.

нашёл причину - PR выше.

конкретно это issue я думаю починено.
